### ISSUE TITLE
Rubberbanding when permission is removed

### ISSUE THREAD

**Issue by SpEeD11** [NoCheatPlus/Issues#314] opened 2016-11-24 11:22 UTC
When adding and removing a permission temporarily (nocheatplus.checks.moving), the player rubberbands when the permission is removed. So for example, if the player is flying through the air at the time (naturally due to gravity), they will rubberband and lose all velocity.

Any idea what could be causing this?

Tested this with the latest build (1035) as well as some older builds.

**Comment by asofold** [comment] 2016-11-24 11:54
Transitions can always be problematic, especially if NCP isn't triggering those, e.g. with external changing of permissions.

Why do you temporarily add/remove that permission? Perhaps it's something that NCP should support anyway, but i can't tell without more details.

**Comment by SpEeD11** [comment] 2016-11-25 05:26
I'm using a custom ability system. Some abilities which launch or pull the player will occasionally rubberband them back to the original location which I have nailed down to be caused by ncp movement checks. Giving them the nocheatplus.checks.moving perm for a few seconds was a simple fix to prevent it.

**Comment by asofold** [comment] 2016-11-25 09:35
There is a couple of edges with that.
* For one thing, NCP is intended to support plugins adding velocity to players.
* Using permissions works without hooking into ncp but is much heavier than using the NCP exemption API. (If you're in full control of exemption, you could use _ncp (un)exempt PLAYER CHECK_TYPE(s)_ .)
* Using nocheatplus.checks.moving (or MOVING for exemption) is VERY wild card. Is there a reason not just to exempt from survivalfly?

If you're just adding velocity, i strongly suggest to create debug logs for issues that an be reproduced (e.g. https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players). We might be able to fix those places, or come up with an alternative to wildcard exemption. Most things could be done via hooking into NCP, and it's still thinkable to add commands to control something that's needed (e.g. to reset some workaround counters, depends on what the issues are).

**Comment by asofold** [comment] 2017-04-19 15:00
Exemption in the current implementation isn't really made for longer term exemption, might also get removed on tick (also by cncp perhaps).

Not sure i mentioned this, you could also add fake velocity entries for a player (MovingData) - one should distinguish, if the player will be using the velocity with typical latency, or if it's just to patch up the next move which you know how it should/could look - in the latter case it's best to directly add vertical/horizontal entries with a minimum activation count set, so they can't be abused to fly elsewhere/longer.

Best is to fix it in NCP. Closing as superseded 'by events' ~ drop a note if there is news/issues.

**Closed by asofold** 2017-04-19 15:00 UTC
