### ISSUE TITLE
DarkLightClient

### ISSUE THREAD

**Issue by CraftCoderr** [NoCheatPlus/Issues#72] opened 2016-01-15 19:39 UTC
Can you fix?
https://youtu.be/dNE-kZJ5CNc?t=71
The most important is ncp fly cheat and antiknockback cheat.
https://www.dropbox.com/s/1nks4sdxx1wwlbr/GriefingRu-Dark_Light_Client_v11.5.zip

**Comment by asofold** [comment] 2016-01-15 22:04
The video is from August 2015. Much has been recoded since then, thinking of build 914 or later as reference.

Such gliding shouldn't be possible, currently there might be a workaround not modeled tight enough, so they could glide at the same height for a short while (not 100% confirmed, possibly fixed soon). Given the new design of handling the vertical part of a move, the glide stuff should be history mostly. A couple of workarounds will be confined further, so they can't be used more times than intended.

Anti knockback won't be fixed soon. It's very likely to create false-positives, if not done 100% right. We will likely focus on certain side-conditions where it is easy to be 100% right, so it's certainly not impossible to catch some of it. 

Current focus is consolidating moving checks for release and starting to redo parts of the fight checks.

**Comment by CraftCoderr** [comment] 2016-01-16 06:40
Now NCPFly fixed, but sometimes NCP not detect this cheat. 
AntiKnockback cheat very strong and requires fix. How it works? Maybe i have ideas to fix it.

**Comment by asofold** [comment] 2016-01-17 01:57
AntiKnockBack is very simple - you just ignore the velocity packets the server sends to you.

Detecting not using velocity should be possible, if not easy with the current infrastructure (we do track velocity use, to prevent false positives). The problems start with not creating new false positives. One has to account for latency, and after detecting not using velocity, we need to know if the player actually could have used the velocity, which means we need to track to which sides the player may have been blocked. It boils down to 'if the player has been blocked towards a certain direction, not using that component of velocity may have been justified'. There may be more edge cases to consider, though.

We might also need to check for using the rough amount of velocity (not just one block to the side), which means extending the area to check for blocks by a lot per move. And we might need to track if the player reduces speed by more than is realistic (friction based modeling). After all we might also have to relate vertical component to horizontal components of velocity, in fact we might have to account for the exact direction there - that would boil down to recoding the entire horizontal axis handling to friction-based + direction of velocity.

Part of probably necessary changes are sort of decided on, but it's not too simple and we have more urgent stuff right now (not using velocity is easy to observe, video/mods).

**Comment by CraftCoderr** [comment] 2016-01-18 04:49
Thanks! I'll think about it.

**Comment by asofold** [comment] 2016-01-18 09:25
Duplicates https://github.com/NoCheatPlus/Issues/issues/22 for the noknockback (updated description to represent current state of thought).

For gliding - i assume it's fixed, we'd also want individual tickets rather. It's in focus anyway and there'll be following more adjustments.

**Closed** 2016-01-26 23:56 UTC
Labels: (a) question/info, (c) cheat/bypass, (c.1) moving, (p.1) NoCheatPlus, (r.2) duplicate
