### ISSUE TITLE
Interact visible false positives

### ISSUE THREAD

**Issue by Kira07** [NoCheatPlus/Issues#78] opened 2016-01-22 14:44 UTC
This check sometimes rollback blocks while mining

**Comment by MyPictures** [comment] 2016-01-23 22:02
Yeah I could reproduce this too on:
21:40:35 INFO: ---- Version information ----
21:40:35 INFO: #### Server ####

21:40:35 INFO: (detected: 1.8.8)
21:40:35 INFO: #### NoCheatPlus ####
21:40:35 INFO: Plugin: 3.13.6-SNAPSHOT-sMD5NET-b920
21:40:35 INFO: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3

21:40:35 INFO: blocks: BlocksMC1_4(base) | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
21:40:35 INFO: checks: FastConsume | Gutenberg
21:40:35 INFO: defaults: pvpKnockBackVelocity
21:40:35 INFO: Hooks: AllViolations(NCP) 1.0 | TestNCPHook 1.0

**Comment by asofold** [comment] 2016-01-24 22:11
@MyPictures The server version got lost :p. What could be reproduced? This is very general...

It's known that keeping the button pressed on changing between block corners will trigger false positives on blockinteract.visible.

It's possible, if NCP or another plugin cancels a block break for very fast breaking blocks, e.g. with efficiency 5 picks on stone, or with higher latency, you might trigger blockinteract.visible for breaking the block behind the block for which breaking just had been cancelled, due to that first block still being there.

For the latter, the best we could do would be to cancel the block break, but not escalate/trigger a violation.That would mean keeping track of 'almost broken' blocks, and might allow people creating server load without getting kicked.

The first might be easier to take care of. Currently visible will trigger, even if you're just slightly off the target block with your looking direction (server- or rather plugin-side). We might change it to allow to be slightly off, though i am not sure if ray-tracing should be done that way, because it's something else to hit a very close block than to hit the block (needs evaluating possible cases etc., correcting the position to the closest on-block thing is also possible - the old implementation used up to 9 alternative positions, which was very interesting, but also might mean much more cpu use).

**Comment by Kira07** [comment] 2016-01-24 23:43
The issue is that a lot of players complained about "rollbacks" while
mining..

2016-01-24 22:11 GMT+00:00 asofold <notifications@github.com>:

**Comment by asofold** [comment] 2016-01-25 10:07
'Rollbacks during mining' could also be other checks (blockbreak.frequency/fastbreak with too much client-side lag).

Are reports containing details about the used tools and the blocks mined? Is it about fast breaking blocks, up/down/anything?

**Comment by Kira07** [comment] 2016-01-25 16:07
It isn't, I checked with the command to see latest violations and it was
this check, when I disabled it the rollbacks vanished.
To reproduce it simply enable the check and go mining with a diamond
pickaxe and a non-op account, pretty easy to reproduce, just mine the
blocks around you for 1mn and you'll see some blocks repop from time to
time.

2016-01-25 10:07 GMT+00:00 asofold <notifications@github.com>:

**Comment by MyPictures** [comment] 2016-01-25 17:54
@asofold its git-PaperSpigot-861d6c6-75593ab (MC: 1.8.8)

**Comment by asofold** [comment] 2016-01-26 09:22
Build 922 contains an experimental fix on base of ProtocolLib (http://ci.md-5.net/job/NoCheatPlus/changes).

This might get changed around a bit still, but it seems to reduce false positives by a lot for now.

**Comment by asofold** [comment] 2016-03-16 09:24
Some violations are bound to happen with ghost blocks (client assumes it's broken, and breaks the next block, but server side the ghost block is still there, so blockinteract.visible triggers for the block behind. I assume players would notice the ghost block due to not being able to move on, though.

**Comment by asofold** [comment] 2017-05-01 13:14
Closing as fixed (with ProtocolLib) - ghost blocks is another issue.

**Closed by asofold** 2017-05-01 13:14 UTC
Labels: (a) false positive, (c) gameplay/experience, (p.1) NoCheatPlus
