### ISSUE TITLE
DoubleJump + SurvivalFly issues

### ISSUE THREAD

**Issue by JesseFST** [NoCheatPlus/Issues#75] opened 2016-01-19 21:13 UTC
Hello.
I'm having a LOT of difficulty trying to configure SurvivalFly settings to allow a doublejump feature without rubber-banding, and am having a lot of difficulty with this.
The rubber-banding issues mostly occurs when you try to double-jump up a ladder, but does frequently happen when trying to jump between trees or gaps in the ground.

I've looked over the documentation on SurvivalFly, but unfortunately it seems VERY limited, and doesn't help me at all. Rather, it makes me more confused.

So, this is my configuration:

```
survivalfly:
  active: true
  strict: false
  extended:
    vertical-accounting: false
  falldamage: true
  actions: log:flyshort:5:18:f cancel vl>256 log:flyshort:5:18:if cancel vl>512 log:flylong:5:18:cif cancel vl>2000 log:flylong:5:18:cif cancel cmd:kickfly
  hover:
    active: true
    step: 108
    ticks: 124
    loginticks: 19
    falldamage: true
    sfviolation: 512
```

And, this is from the logs when I enabled the debug feature on myself:

-------------- MOVE --------------
JesseTheDemon NCPTest:
from: 125.12400735202888, 108.53903376942856, 138.59193916681244
to: 125.27400735798935, 109.44063378697616, 138.59193916681244
(walkspeed=0.2 flyspeed=1.0)(svel=0.381680964526253,0.710664686041566,0.0)
16-01-10 15:55:11 [FINE]
from flags: IGN_PASSABLE+GROUND+CLIMBABLE
from id=65 data=4 shape=[0.875, 0.0, 0.0, 1.0, 1.0, 1.0]
from below id=65 data=4 shape=[0.875, 0.0, 0.0, 1.0, 1.0, 1.0]
to flags: IGN_PASSABLE+GROUND+CLIMBABLE
to id=65 data=4 shape=[0.875, 0.0, 0.0, 1.0, 1.0, 1.0]
to below id=65 data=4 shape=[0.875, 0.0, 0.0, 1.0, 1.0, 1.0]
16-01-10 15:55:11 [FINE] JesseTheDemon SurvivalFly
ground: resetcond -> resetcond, jumpphase: 0, liftoff: NORMAL(0)
hDist: 0.15(-0.356) / 0.287 hbuf=0 , vDist: 0.902 (-0.098) / 0, sby=108.53903376942856 (0.902 / 1.35)
tags: dirty+climbspeed

16-01-10 15:55:11 [INFO] [VL] JesseTheDemon MOVING_SURVIVALFLY VL=129.5(+61.4) distance=0.91 health=20.0/20.0 locationfrom=125.12, 108.54, 138.59 locationto=125.27, 109.44, 138.59 tags=dirty+climbspeed
16-01-10 15:55:11 [FINE] JesseTheDemon set back to: CraftWorld{name=NCPTest}125.124, 108.539, 138.592
16-01-10 15:55:11 [FINE] JesseTheDemon TP UNKNOWN (set-back): Location{world=CraftWorld{name=NCPTest},x=125.12400735202888,y=108.53903376942856,z=138.59193916681244,pitch=-43.649998,yaw=270.18195}
16-01-10 15:55:11 [FINE] JesseTheDemon Flying(ground=false,x=125.41050736734728,y=110.24580181984359,z=138.59193916681244)
16-01-10 15:55:11 [FINE] JesseTheDemon Flying(ground=false,x=125.12400735202888,y=108.53903376942856,z=138.59193916681244,pitch=-43.649998,yaw=270.18195)
16-01-10 15:55:11 [FINE] JesseTheDemon Flying(ground=false,x=125.12400735202888,y=108.53903376942856,z=138.59193916681244)
16-01-10 15:55:11 [FINE] JesseTheDemon Flying(ground=false,x=125.12400735202888,y=108.46063376790268,z=138.59193916681244)

And, for further information purposes, this is from the /ncp version command.

[15:59:44 INFO](Features:): ---- Version information ----
[15:59:44 INFO](Features:): #.#.#.# Server #.#.#.#

[15:59:44 INFO](Features:): (detected: 1.7.10)
[15:59:44 INFO](Features:): #.#.#.# NoCheatPlus #.#.#.#
[15:59:44 INFO](Features:): Plugin: 3.13.5-BETA-sMD5NET-b914
[15:59:44 INFO](Features:): MCAccess: 1.7.10 / CB3100

[15:59:44 INFO](Features:):   blocks: BlocksMC1_4(base) | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2
[15:59:44 INFO](Features:):   checks: FastConsume | Gutenberg | FlyingFrequency | KeepAliveFrequency | AttackFrequency
[15:59:44 INFO](Features:):   packet-listeners: MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | UseEntityAdapter
[15:59:44 INFO](Features:): Hooks: AllViolations(NCP) 1.0
[15:59:44 INFO](Features:): #.#.#.# Related Plugins #.#.#.#
[15:59:44 INFO](Features:): ProtocolLib v3.6.4

I've posted about this in the Spigot forums, but was advised to post here.
https://www.spigotmc.org/threads/nocheatplus-survivalfly-double-jump.114927/

More specifically, the issue occurs when doublejumping onto ladders, between trees and other structures. Despite the countless hours I've spent in attempting to tweak it, doesn't help at all. I've had to completely disable fly checks since.

I am using my own plugin, for handling Double-Jump, as part of a kit ability in my game mode.
Any help would be GREATLY appreciated!!

**Comment by FstJosh** [comment] 2016-01-19 21:17
If this helps, this is the code in my plugin that handles the actual doublejump.

@EventHandler(priority=EventPriority.HIGH, ignoreCancelled=true)
    public void DoubleJump(PlayerToggleFlightEvent event) {
    	Player player = event.getPlayer();
	double velocity = 0.70;
	double height = 1;
	final Location loc = player.getLocation();
	if ((player.getGameMode() != GameMode.CREATIVE) && (player != null)) {    		
    		event.setCancelled(true);
    		player.setAllowFlight(false);
    		player.setFlying(false);

	        player.setVelocity(loc.getDirection().multiply(velocity).setY(height));
    	}
    }

**Comment by FstJosh** [comment] 2016-01-19 21:38
Also, attached is the debug logs.
[nocheatplus.txt](https://github.com/NoCheatPlus/Issues/files/96594/nocheatplus.txt)

**Comment by asofold** [comment] 2016-01-19 22:53
The violation posted first is a little bit odd, because it's about the ladder/climbable sub-check (tags: dirty+climbspeed). Either they allow vertical velocity on ladders or the bounding box assumed by NCP isn't right (can't dig in right now).

Otherwise looks odd, e.g. added velocity  mentioned in line 8710 is not showing up as queued vertical velocity until the violation at line 8756. Need to investigate further, if there may be some kind of reset conditions, at least it's not due to a transition between different fly checks.

**Comment by Adondriel** [comment] 2016-02-11 21:17
I need this solved as well, I use a "grappling hook" type of item on my server and my players can't use the grappling hook while on ladders, because it will end up kicking them.

**Comment by asofold** [comment] 2016-02-15 11:42
I think this needs to be fixed with a special case rather, as normal players can't move such ways on ladder, even not with velocity (correct me if i am mistaken).

**Comment by Adondriel** [comment] 2016-02-15 21:06
I would agree, just check to see, "is velocity the thing that is moving this player?" they seem to have fixed this for everything other than water and ladders, in which they are both buggy. I have fixed the water issue by changing swimmingspeed to 150%, but it would be nice to have a check so that I don't have to do that either.

**Comment by asofold** [comment] 2016-02-16 11:42
Technically, velocity + water should be supported by default. Not sure if the toggle-flight part adds more than the velocity does, and isn't accounted for - NCP assumes the event to be like adding velocity.

For the ladder i need to somehow reproduce this, to distinguish:
* Is it a bounding box issue (NCP assumes you to be on ladder, but you're just off by a bit)?
* Should vertical velocity work, when clearly on a ladder (i assume not)?
* Is the extra bit of vertical distance added due to toggle-flight an issue?

The violation log messages posted above indicate, that velocity is fully used, however the log starts late (just seeing that now), we need the 'new velocity' entry too. @JesseFST Do you still have the log from the first violation you posted here? We'd need more entries before the first shown one.

event.setCancelled(true); This might let NCP ignore the effect by the toggling flight itself, it doesn't really touch the bounding box question with ladders, though.

(player.getGameMode() != GameMode.CREATIVE) && (player != null)) <- Test for null first :p.

**Comment by Adondriel** [comment] 2016-02-17 01:11
The issue is that, they are on a ladder, my plugin (using skript) uses velocity to push the player in the direction they are looking, if they look up, to go up the ladder faster it thinks they are hacking. So in my case, it would check if velocity is the cause of movement (not sure if we can do that), and then allow them if so, if they are on a ladder.

If you would like to see how it works or need the code for this, let me know I can send it to you privately.

**Comment by Adondriel** [comment] 2016-02-18 17:21
Specifically this point:
Should vertical velocity work, when clearly on a ladder (i assume not)?
Yes, vertical velocity should work in this case, but this should probably be a config toggle?

**Comment by JesseFST** [comment] 2016-02-18 17:26
Sadly, I do not have the previous logs from the 1st violation.
I can get more, recent ones though, if you'd like.

**Comment by asofold** [comment] 2016-02-18 23:41
@JesseFST New logs are perfectly fine. Don't hesitate to post a lot of context / a couple of violations. Could use gist/paste to link.

**Comment by asofold** [comment] 2016-02-18 23:46
@Adondriel It could be made a special setting, possibly wouldn't hurt. However we don't know the next move, as currently NCP prevents the first move. So after using velocity once, would you move on like in-air on ladders, with air-like friction? Usually not... so i assume the actual problem is the bounding box, or perhaps a specialty with velocity counting once, if you're on ground otherwise. Or perhaps with 1.8.9 or so they changed velocity to work on ladder.

For reproducing the issue, it  could also help to know how far you've been off the ladder (edge of where you can climb up, clearly on the ladder where you can climb up, or just off the ladder so you can't climb up...

**Comment by JesseFST** [comment] 2016-02-19 00:08
Alright. I'll test it out later tonight or tomorrow and post back.
I'll also record a video of it happening, so you can see the specific details you mentioned in your comment to Adondriel. It may help with distance, etc.

**Comment by andrewchi12345** [comment] 2016-03-15 09:01
Im having similar problems, when setting velocity to a player, sometimes it triggers survival fly, sometimes it does not.

**Comment by asofold** [comment] 2016-03-15 21:44
@andrewchi12345 A custom plugin under your control? Could you provide a debug log containing a range of incidents with false positives (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players)?

**Comment by asofold** [comment] 2017-05-02 21:17
Closing as superseded, as many things have changed since.

If ussues are persisting, or you want to get rid of a too broad custom exemption, feel free to open a new issue, preferably with a debug log (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) of how this does not work with the latest of NCP.

**Closed by asofold** 2017-05-02 21:17 UTC
Labels: (a) bug, (a) false positive, (c) gameplay/experience, (c.1) moving, (p) compat/external, (p.1) NoCheatPlus, (q.1) WANTED, (r) superseded
