### ISSUE TITLE
survival-fly double-piston stuck in block

### ISSUE THREAD

**Issue by i9hdkill** [NoCheatPlus/Issues#66] opened 2015-12-30 00:13 UTC
Nocheat plus config:
http://pastebin.com/dDn8y2ut
nocheatplus version:
http://pastebin.com/Mpp4G3L2
protocolib build 201

Setup:
http://prntscr.com/9k2tcm

A non OP player pushes the button to activate the double pistons:
http://prntscr.com/9k2rye
both stickypistons should push the player back up on the floor, but the player is stuck
http://prntscr.com/9k2rk4

If you repeat this with a player that has nocheatplus bypass/admin permissions, everything is working fine without being stuck in the floor.

Issue 2
this piston with a slime block should move players up to 6 blocks into the air. But that does not work
http://prntscr.com/9k2x4n
(Is working for OP players

**Comment by asofold** [comment] 2015-12-30 12:25
This should be a duplicate of: https://github.com/NoCheatPlus/Issues/issues/5

Updated title and description of https://github.com/NoCheatPlus/Issues/issues/5 for easier search. Work is in progress, but it's somewhat complex/nasty.

**Comment by asofold** [comment] 2016-01-07 10:25
Closing as duplicate. Please refer to ticket https://github.com/NoCheatPlus/Issues/issues/5 for tracking progress.

**Closed by asofold** 2016-01-07 10:26 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus, (r.2) duplicate
