### ISSUE TITLE
Boat Bug?

### ISSUE THREAD

**Issue by RainOfPain125** [NoCheatPlus/Issues#517] opened 2018-03-01 20:49 UTC
#### Short description of the issue.
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
#### Complete output of the _ncp version_ command (please prefer text here).
[15:47:25 INFO]: ---- Version information ----
[15:47:25 INFO]: #### Server ####
[15:47:25 INFO]: git-Paper-1329 ~MC: 1.12.2~
[15:47:25 INFO]:   detected: 1.12.2
[15:47:25 INFO]: #### NoCheatPlus ####
[15:47:25 INFO]: Plugin: 3.16.1-SNAPSHOT-sMD5NET-b1142
[15:47:25 INFO]: MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
[15:47:25 INFO]: Features:
[15:47:25 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
[15:47:25 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[15:47:25 INFO]:   defaults: pvpKnockBackVelocity
[15:47:25 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[15:47:25 INFO]: Hooks: AllViolations~NCP~ 1.0 | Citizens2~cncp~ 2.0 | mcMMO~cncp~ 2.3
[15:47:25 INFO]: #### Related Plugins ####
[15:47:25 INFO]: CompatNoCheatPlus v6.6.5-SNAPSHOT-sMD5NET-b89 | ProtocolLib v4.4.0-SNAPSHOT-b390
#### How to reproduce the issue (is it random / always happens / side conditions)?
Always happens when a user is moving at max speed in a boat
#### Have you made any (noteworthy) changes to the default configuration of NCP?
Yes, but the config creator claimed it isn't his fault. [Config here](https://www.spigotmc.org/threads/nocheatplus-config-optimized-and-free.158041/page-33)
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Not really.. The biggest game-changing plugin we have is McMMO
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Again,
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!
[03:22:14 WARN]: Boat (vehicle of JoeKai) moved wrongly!

**Comment by asofold** [comment] 2018-03-01 21:55
The moved wrongly messages come from the vanilla server as well. It used to be very easy to get them on 1.11/1.12 with horses on (larger setups of) stairs as well.

I assume NCP isn't even involved - is there NCP violation logs for the same time ?

**Comment by RainOfPain125** [comment] 2018-03-02 02:46
NCP violation logs as in?

**Comment by 0-x-2-2** [comment] 2018-03-02 04:28
I believe spigot/paperspigot added some sort of "anticheat" for boats moving wierd ways (this is nothing todo with ncp)

**Comment by asofold** [comment] 2018-03-05 11:31
Well ncp violation logs may be in the nocheatlus log file - it would be interesting if  'moved wrongly' messages appear about the same time.

In general moved wrongly can happen a lot (horses on stairs, boats in odd constellations ~ water falls, edges of blocks near).

**Comment by asofold** [comment] 2018-05-09 08:02
Closing as 'invalid', assuming it's just due to vanilla. It might be a loop with both vanilla server and ncp affecting each other, but in that case we'd need logs that show a difference that ncp makes (server log and NCP .. violation log or debug log or 'ncp info _player_' before + after reproducing.

**Closed as completed by asofold** 2018-05-09 08:02 UTC
Labels: (r.2) invalid, (a) question/info, (c.1) moving, (c) gameplay/experience, (p.1) NoCheatPlus
