### ISSUE TITLE
Glitching with Trapdoors (1.9)

### ISSUE THREAD

**Issue by TheFeldi** [NoCheatPlus/Issues#167] opened 2016-04-29 10:46 UTC
I recorded it. Must be reproduceable. With my autobansystem, thats fatal!
Youtube Link: https://youtu.be/tZ8-Tx8IK-o

Log of the loggingthingy

16-04-29 12:29:21 [FEIN] [MOVING_NOFALL] [Konstrukt] NoFall: mc=0.22476299 / nf=0.45245147 (+0.2276884764432907) | ymax=76.24918707874468
16-04-29 12:29:21 [FEIN] [MOVING] [Konstrukt] MOVE in world world:
from: 765.6999999880791, 75.79673560066871, 811.6860299660549
to: 765.6999999880791, 75.49520087700593, 811.6860299660549
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.30153472366278034,0.0)
16-04-29 12:29:21 [FEIN] 
from flags: SOLID+IGN_PASSABLE+GROUND
from id=96 data=2 shape=[0.0, 0.0, 0.0, 1.0, 0.1875, 1.0]
from below id=65 data=4 shape=[0.8125, 0.0, 0.0, 1.0, 1.0, 1.0]
to flags: SOLID+IGN_PASSABLE+GROUND+CLIMBABLE
to id=96 data=2 shape=[0.0, 0.0, 0.0, 1.0, 0.1875, 1.0]
to below id=65 data=4 shape=[0.8125, 0.0, 0.0, 1.0, 1.0, 1.0] (ground within 0.5)
16-04-29 12:29:21 [FEIN] [MOVING_SURVIVALFLY] [Konstrukt] 
onground: --- -> ---, jumpphase: 8, liftoff: NORMAL(0)
 hDist: 0 (0) / 0 , vDist: -0.302 (-0.074) / -0.286 , sby=75.0 (0.495 / 1.35) , fdsq: 1.754
 vacc=|-0.302/1|-0.452/3|0/0|
 tags: elytra_off

16-04-29 12:29:21 [FEIN] [MOVING_NOFALL] [Konstrukt] NoFall: mc=0.45245147 / nf=0.7539862 (+0.3015347123146057) | ymax=76.24918707874468
16-04-29 12:29:21 [FEIN] [MOVING] [Konstrukt] MOVE in world world:
from: 765.6999999880791, 75.49520087700593, 811.6860299660549
to: 765.6999999880791, 75.1875, 811.6860299660549
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.3739040364667221,0.0)
16-04-29 12:29:21 [FEIN] 
from flags: SOLID+IGN_PASSABLE+GROUND+CLIMBABLE
from id=96 data=2 shape=[0.0, 0.0, 0.0, 1.0, 0.1875, 1.0]
from below id=65 data=4 shape=[0.8125, 0.0, 0.0, 1.0, 1.0, 1.0] (ground within 0.5)
to flags: SOLID+IGN_PASSABLE+GROUND+CLIMBABLE
to id=96 data=2 shape=[0.0, 0.0, 0.0, 1.0, 0.1875, 1.0]
to below id=65 data=4 shape=[0.8125, 0.0, 0.0, 1.0, 1.0, 1.0]
16-04-29 12:29:21 [FEIN] [MOVING_SURVIVALFLY] [Konstrukt] 
onground: --- -> onground, jumpphase: 9, liftoff: NORMAL(0)
 hDist: 0 (0) / 0 , vDist: -0.308 (-0.006) / -0.358 , sby=75.0 (0.188 / 1.35) , fdsq: 1.041
 tags: elytra_off

16-04-29 12:29:21 [FEIN] [MOVING_NOFALL] [Konstrukt] NoFall: mc=0.0 / nf=0.0 | ymax=75.49520087700593

**Comment by asofold** [comment] 2016-04-29 12:25
Looks like it's a trapdoor above a ladder and the player is wearing but not using elytra, and there is no set-back contained in the log. Just a quick glance.

Could you give us more text? Specifically i am interested in:
* Output of the 'ncp version' command. _Might be in the video, will watch later. Still should be as text here whenever possible._
* A longer log containing valid moves from before glitching and as much of the glitching as possible (up to a couple of seconds, multiple set-backs contained if possible). A gist or a link to a zip file should do.

**Comment by asofold** [comment] 2016-05-16 20:03
Looks like it's easy to reproduce.

Also looks like some standard measures don't work here, such as adding ground_height to the block flags via configuration.

Could be a bounding box issue (nasty, because altering those can affect many things), might have to special case it for the vdistrel sub check of survivalfly.

**Comment by asofold** [comment] 2016-06-06 15:27
Fix attempt in build 989.

**Comment by asofold** [comment] 2016-06-11 15:12
Build 1005 contains more fixes that might be related to trap door. Closing as 'fixed' now.

**Closed by asofold** 2016-06-11 15:12 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus, (q.2) IMPORTANT, (r) fixed
