### ISSUE TITLE
Blocking Ignite Event?

### ISSUE THREAD

**Issue by L4BORG** [NoCheatPlus/Issues#435] opened 2017-05-03 01:19 UTC
#### Short description of the issue.
Players can not light up nether portals (with flint and steel) anymore.

#### Complete output of the _ncp version_ command (please prefer text here).
```
>ncp version
[03:18:16 INFO]: ---- Version information ----
[03:18:16 INFO]: #### Server ####
[03:18:16 INFO]: git-TacoSpigot-"65fd35f" ~MC: 1.8.8~
[03:18:16 INFO]:   detected: 1.8.8
[03:18:16 INFO]: #### NoCheatPlus ####
[03:18:16 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1091
[03:18:16 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[03:18:16 INFO]: Features:
[03:18:16 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[03:18:16 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[03:18:16 INFO]:   defaults: pvpKnockBackVelocity
[03:18:16 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[03:18:16 INFO]: #### Related Plugins ####
[03:18:16 INFO]: ProtocolLib v3.6.5 | ViaVersion v1.0.5-SNAPSHOT
```

#### How to reproduce the issue (is it random / always happens / side conditions)?
It's always there (it works for OPs, prob. cause they have bypass).

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
No.

**Comment by asofold** [comment] 2017-05-03 10:05
Are you sure it is due to NCP ? I can't reproduce it on 1.11.2.

Will retry with 1.8.8 though.

**Comment by L4BORG** [comment] 2017-05-03 10:08
Yes, after downgrading to NCP b1084 I can activate netherportals using flintandsteel again.

**Comment by asofold** [comment] 2017-05-03 10:50
Reproduced on 1.8.8 - it'll trigger blockplace.against.

**Comment by asofold** [comment] 2017-05-03 12:01
Should be fixed in build 1096.

**Closed as completed** 2017-05-30 21:37 UTC
Labels: (a) false positive, (r) fixed, (c.1) moving, (c) gameplay/experience, (p.1) NoCheatPlus
