### ISSUE TITLE
Rubberbanding during parkour

### ISSUE THREAD

**Issue by MidnightSugar** [NoCheatPlus/Issues#325] opened 2016-12-10 03:24 UTC
#### Short description of the issue.
People are getting rubberbanded during parkour. I can see them do a jump, then they get teleported backwards. It seems to be called a "set back" in the debug logs.

#### Complete output of the _ncp version_ command (please prefer text here).
09.12 21:26:44 [Server] INFO ---- Version information ----
09.12 21:26:44 [Server] INFO #### Server ####
09.12 21:26:44 [Server] INFO git-Spigot-f950f8e-0fa1ad2 ~MC: 1.11~
09.12 21:26:44 [Server] INFO detected: 1.11
09.12 21:26:44 [Server] INFO #### NoCheatPlus ####
09.12 21:26:44 [Server] INFO Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1041
09.12 21:26:44 [Server] INFO MCAccess: 1.4.5-1.11|? / CB-Reflect
09.12 21:26:44 [Server] INFO Features:
09.12 21:26:44 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
09.12 21:26:44 [Server] INFO checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
09.12 21:26:44 [Server] INFO defaults: pvpKnockBackVelocity
09.12 21:26:44 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
09.12 21:26:44 [Server] INFO Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
09.12 21:26:44 [Server] INFO #### Related Plugins ####
09.12 21:26:44 [Server] INFO CompatNoCheatPlus v6.6.3-SNAPSHOT-sMD5NET-b86 | ProtocolLib v4.2.0-SNAPSHOT-b331

#### How to reproduce the issue (is it random / always happens / side conditions)?
Fairly random. I get notified of it mostly during the parkour. Especially during jumps that involve pistons.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Yes I have changed a lot. All configuration changes were from here:
[http://www.mc-market.org/resources/475/](url) I do not have permission to put the config here.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Full List of Plugins:
CoreProtect
KeepItems
XrayDetector
GroupManager
MonsterFix
Votifier
ProtocolLib
LibsDisguises
ChatReaction
SafariNet
FastAsyncWorldEdit
Edit_Mobs
EpicWorldGenerator
SuperbVote
mcMMO
Vault
InfernalMobs
dynmap
WorldEdit
Essentials
CompatNoCheatPlus
WorldBorder
PlotSquared
CrateReloaded
DeathCharge
WorldGuard
Multiverse-Core
TreasureChest
React
EssentialsChat
Shop
EssentialsSpawn
GriefPrevention
EnjinMinecraftPlugin
WorldGuardExtraFlags
TitleManager
AreaShop
HyperDrive
SilkSpawners
JDynmapGriefPrevention
ShopGUIPlus

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Debug log of issue:
16-12-09 21:06:49 [INFO] [VL] [MOVING_SURVIVALFLY] [Retrack421] [->[Member] Retrack421] VL=210(+0.6) health=20.0/20.0
16-12-09 21:06:49 [FINE] [MOVING_NOFALL] [Retrack421] NoFall deal damageviolation: 4.846024513244629
16-12-09 21:06:49 [FINE] [MOVING] [Retrack421] Damage(FALL): 4.846024513244629 / dist=6.9405923 nf=6.9405923 yDiff=6.9405923
16-12-09 21:06:49 [FINE] [MOVING] [Retrack421] Set back to: CraftWorld{name=Christmas}1,971.3, 37, 1,175.93
16-12-09 21:06:49 [FINE] [MOVING] [Retrack421] TP UNKNOWN (set back): Location{world=CraftWorld{name=Christmas},x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=33.600056,yaw=210.23174}
16-12-09 21:06:49 [FINE] [NET] [Retrack421] Expect ACK on outgoing position: CountableLocation(x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=33.600056,yaw=210.23174,count=1)
16-12-09 21:06:49 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.8831360989425,y=30.0,z=1174.4964593548143)
16-12-09 21:06:49 [FINE] [NET] [Retrack421] Incoming packet, interpret as ACK for outgoing position.
16-12-09 21:06:49 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=33.600056,yaw=210.23174)
16-12-09 21:06:49 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.300000011921,y=37.0,z=1175.9302639555124)
16-12-09 21:06:49 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.300000011921,y=36.92159999847412,z=1175.9302639555124)
16-12-09 21:06:49 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.300000011921,y=36.76636799395752,z=1175.9302639555124)
16-12-09 21:06:49 [FINE] [MOVING] [Retrack421] MOVE in world Christmas:
From: x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=33.600056,yaw=210.23174
To: x=1971.300000011921,y=36.92159999847412,z=1175.9302639555124,pitch=33.600056,yaw=210.23174
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-1.406611164032995,-0.004098058943697706)(e_depth_strider=3.0)
16-12-09 21:06:49 [FINE]
16-12-09 21:06:49 [FINE] [MOVING_SURVIVALFLY] [Retrack421]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078 , sby=37.0 (-0.078 / 0.0)
tags: data_reset

16-12-09 21:06:48 [INFO] [VL] [MOVING_SURVIVALFLY] [Retrack421] [->[Member] Retrack421] VL=209.4(+209.4) health=20.0/20.0
16-12-09 21:06:48 [FINE] [MOVING] [Retrack421] Set back to: CraftWorld{name=Christmas}1,971.3, 37, 1,175.93
16-12-09 21:06:48 [FINE] [MOVING] [Retrack421] TP UNKNOWN (set back): Location{world=CraftWorld{name=Christmas},x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=32.250053,yaw=192.08173}
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Expect ACK on outgoing position: CountableLocation(x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=32.250053,yaw=192.08173,count=1)
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Incoming packet, still waiting for ACK on outgoing position.
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Incoming packet, interpret as ACK for outgoing position.
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.68407085802,y=37.7531999805212,z=1170.8518128671078,pitch=32.400055,yaw=-166.26826)
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Incoming packet, interpret as ACK for outgoing position.
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=32.250053,yaw=192.08173)
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.3053321642801,y=37.0,z=1175.9053481280741,pitch=32.250053,yaw=192.08173)
16-12-09 21:06:48 [FINE] [NET] [Retrack421] Flying(ground=false,x=1971.3161026767457,y=36.92159999847412,z=1175.857891571365,pitch=32.400055,yaw=193.43173)
16-12-09 21:06:48 [FINE] [MOVING] [Retrack421] Split move 1 (from -> loc):
16-12-09 21:06:48 [FINE] [MOVING] [Retrack421] MOVE in world Christmas:
Location: x=1971.3053321642801,y=37.0,z=1175.9053481280741,pitch=32.250053,yaw=192.08173
From: x=1971.300000011921,y=37.0,z=1175.9302639555124,pitch=32.250053,yaw=192.08173
To: x=1971.3053321642801,y=37.0,z=1175.9053481280741,pitch=32.250053,yaw=192.08173
(walkspeed=0.2 flyspeed=0.1)(sprinting)(svel=0.0,-0.44749789698341763,-0.018531719726180135)(e_depth_strider=3.0)
16-12-09 21:06:48 [FINE]
16-12-09 21:06:48 [FINE] [MOVING_SURVIVALFLY] [Retrack421]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
hDist: 0.025 / 0.302 hbuf=0 , vDist: 0 / 0 , sby=37.0 (0 / 0.0)
hacc: 1.104(18)
tags: data_reset

**Comment by asofold** [comment] 2016-12-10 12:57
Is that one piece of the log or two small sections copied?

If it doesn't matter to you i'd prefer to always see contiguous sequences, and they may well be much longer - you could attach such a log/sequence as a zipped text file right underneath, there should be a small blue dashed line just below with the text "Attach files by dragging & dropping or selecting them" (you can click on "selecting them").

Concerning jumps with pistons - a little patience :) - i'm trying to bring in a bleeding edge build with improved piston support (concerns ground, passing through, moves resulting from vertical push/pull - _but not moves resulting from horizontal push/pull).

Issue for block change tracking: https://github.com/NoCheatPlus/Issues/issues/5

**Comment by MarkElf** [comment] 2016-12-10 21:50
@MidnightSugar Please remove my work from your original post; you have no right to be sharing my work with others without my consent.

**Comment by MarkElf** [comment] 2016-12-10 22:41
@MidnightSugar Please remove my work from your original post; you have no right to be sharing my work publicly, especially without my consent. Instead, attempt to reproduce the issue with the default configuration to check if that has any impact on your situation. If would rather have players fall directly downwards rather than being teleported to the last solid block that they were on, I recommend dropping NTAC + NTApi onto your server.

**Comment by MidnightSugar** [comment] 2016-12-10 23:09
@MarkElf Sorry. I have removed it from the post.

**Comment by asofold** [comment] 2016-12-11 00:24
@MarkElf For one thing i am happy with people investing time into configuration, on the other hand it's a little bit peculiar to have a paid configuration (potentially) dominate our bug tracker by "you may not post that" :p. While NoCheatPlus is licensed with GPLv3, i am not entirely sure what the runtime-generated configuration is licensed with officially. If it has "no license", it'll wildly vary amongst countries, e.g. in germany "no license" doesn't even exist (AFAIK), so would it be "all rights reserved" (to me and/or to past contributors!?/, in this case :p). Even if it was GPLv3, i am not entirely sure  if those who buy it from you are allowed tro publish it (could wildly vary by country) - my assumption being, that i'd have to enforce the GPLv3 on you :p, in order to put things "right". If i demanded you to come into complicance with GPLv3, you could drop your paid offer and remove it from the market, for one thinkable result, or perhaps the auto-generated configuration is not regarded as licensed at all. On the other hand all alterations to the configuration (say, excluding comments), are usually not so special in nature, and it could really turn out to be a problem to go nitpicking here. I am undecided concerning what to do, e.g. one could think of offering a special license for configuration, with terms that help all of us, or we could attempt to integrate you into the project, e.g. activating donations and sharing them (this is complicated  for me, potentially, due to the by-hearsay overly idiotistic german tax law). So in essence i'll probably do nothing right now, but i want you to know that it's a fundamental, yet probably not so big dilemma, since we profit from reports using the default configuration most (not in terms of money), anyway. I will inform myself to get an idea about what i can do with donations and what i can not do (which probably means to pay a lawyer) - concerning configuration i am somewhat undecided, as apparently i don't have the resources to test things out on all sorts of server types myself, while not few people seem to regard the configuration as a 'much secret thing' , contribution towards improving the default configuration has always been few. An answer to that could be to make NCP perfect :p, so there is no need to have any special configurations of such impact, or we let people do paid configuration offers and/or what-not else there may be. I assume this issue ("mostly with pistons involed") to be of a non-typical kind, though.

@MidnightSugar If this could be reproduced with the default configuration, that would be best for all, at this stage.

With recent jurisdiction in germany (HUMBUG +- two letters :p)  things may go down the drain quickly anway :p. My hope for this situation is, that it's about the website owner having been notified by the rights owner and having decided to ignore that. In that case, i.e. an explicit notification (email!?, letter?, letter of marque?!?), it wouldn't be the end of the internet in Germany. Just all orphan sites get extinguished quickly :), as well as non-maintained sites. On the other hand, what do you do if a lawyer/thingy tells you to pay 1000$ to forget about 'the issue'... i would send a nuke, after reassuring it's far away enough - but not everybody can actually call that option their own.

**Comment by MarkElf** [comment] 2016-12-11 00:58
@asofold I've always had bright intentions with any long-term project that I begin to work on. I would prefer not to share those intentions here as this isn't the time or place to do so; if you would like to continue this conversation, you are more than welcome to drop me a message via Spigot @ MarkElf2204 where I can gladly expand upon my thoughts, as well as this conversation in private with you.

**Comment by asofold** [comment] 2016-12-11 20:42
@MarkElf Sure, i don't intend to make a random ticket place of a discussion. Perhaps i could've made the text shorter,  but it's not a 100% optimal situation with anti cheating these days. Most _developers_ seem to be hidden or are busy with making $ with pattern matching like technique (e.g. 'entities'), and are keeping secrets closed source + obfuscated. I'm not interested in those secrets, but if the narrative of "NCP + good (paid) configurations" keeps pushing, i'm not so sure if the best thing is to just keep plodding on, because i can't really support decreasing contribution to NCP under the current side conditions. In fact you've been contributing actively otherwise on various occasions, so don't take this as a personal/too much directed thing, i just think that  the questions about contribution and licensing somehow have to be settled for open-source to make sense.

Having more text again, i just let this stay here for reference, and relay further discussion to spigotmc/pm.

**Comment by asofold** [comment] 2017-05-01 13:24
Closing as suprseded - varying issues for which other tickets may be in place.

**Closed by asofold** 2017-05-01 13:24 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus
