### ISSUE TITLE
Missing configurable messages (very minor)

### ISSUE THREAD

**Issue by bonces** [NoCheatPlus/Issues#251] opened 2016-07-26 02:05 UTC
There are many kick messages that aren't in the config to be configurable, in the default generated config. It would be nice if all of them where in the config to be customized and work with color codes.

**Comment by asofold** [comment] 2016-08-02 21:45
Could see this as a part-duplicate of: https://github.com/NoCheatPlus/Issues/issues/46

It's clearly missing, having extra language file(s).

**Closed** 2017-01-19 02:27 UTC
