### ISSUE TITLE
Spam in the console

### ISSUE THREAD

**Issue by Skilzar** [NoCheatPlus/Issues#401] opened 2017-04-03 07:06 UTC
#### Short description of the issue.

Hello! :)
I went to a random place and started spamming into the console.
Log started to weigh as much as 52 megabytes!

[09:01:13] [Server thread/ERROR]: Could not pass event VehicleUpdateEvent to NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1070
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityMinecartAbstract.t_(EntityMinecartAbstract.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException

#### Server ####
git-Spigot-21fe707-e1ebe52 ~MC: 1.8.8~
  detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1070
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
  checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.1.0

#### How to reproduce the issue (is it random / always happens / side conditions)?

Random

#### Have you made any (noteworthy) changes to the default configuration of NCP?

Default

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

ViaVersion

**Comment by asofold** [comment] 2017-04-03 09:51
Is the error stack trace really complete?

I'm missing the NCP related parts, except for "could not pass .. event".

Likely it's below the last line shown here: "Caused by: java.lang.NullPointerException" If the text is too long for here, you can always create a gist (https://gist.github.com/) or upload a text file here. Adding the bit just above is ok for me, i hope you still have that log.

**Comment by Skilzar** [comment] 2017-04-03 10:27
I deleted that log, it weighed about 100 megabytes.
But I was able to cause this error again. I teleported to a random place and again this error.
[12:19:02] [Server thread/ERROR]: Could not pass event VehicleUpdateEvent to NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1070
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityMinecartAbstract.t_(EntityMinecartAbstract.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at fr.neatmonster.nocheatplus.compat.bukkit.EntityAccessVehicleLegacy.getEntityPassengers(EntityAccessVehicleLegacy.java:21) ~[?:?]
	at fr.neatmonster.nocheatplus.utilities.entity.PassengerUtil.getFirstPlayerPassenger(PassengerUtil.java:81) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.vehicle.VehicleChecks.onVehicleUpdate(VehicleChecks.java:274) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	... 13 more

**Comment by asofold** [comment] 2017-04-03 11:29
Thank you :). This should be fixed with build 1071.

**Closed** 2017-04-05 18:58 UTC
Labels: (a) bug, (c.1) moving, (p.1) NoCheatPlus, (r) fixed
