### ISSUE TITLE
Jesus / waterwalk  [DBO 766]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#34] opened 2015-12-06 16:29 UTC
**This ticket is only about the cosmetic appearance, for the speeding aspect please refer to the 'horizontal speeding' issue: https://github.com/NoCheatPlus/Issues/issues/7**

==What is the problem? What do you expect to see instead?==
Players can slowly walk on water (without the conventional jumping "bypass"), stand on water, and walk backwards at full speed on water as if it were a solid block (on my localhost server). On public/production servers with NCP, I am able to sprint on the water. The player should be swimming in the water and not able to stand on it.

==Can it be reproduced systematically and if so: How?==
With a client.

==How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?==
Easy with a client.

==**Versions of NCP+MCAccess and server: Post the full output of the "ncp version" command!**==
Server: git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks (MC: 1.7.5)
NCP: 3.10.12-RC-sMD5NET-b700
MCAccess: 1.7.5 / CB3026
Hooks: TestNCPHook 1.0

==Details about the configuration file of NCP.==
//(Examples: What version of NCP was the config generated with? Did you change anything - if so: add a quick description.)//\
Default

==Do you run any other special plugin next to NC+ (adding skills, machines, adding/changing blocks)?==
//(Examples: SpoutPlugin, mcMMO, Heroes, MachinaCraft and others.)//\
Nope

==Please provide any additional information below!==
//(Examples: Logs, screenshots, plugin list, player amount, NCP configuration files ... use http://dev.bukkit.org/paste/ or http://pastebin.com/ and add the link here if linked resources are longer than a few lines.)//\

Here is the SRC to the "bypass" - http://pastebin.com/WtLA7ugR

**Comment by MyPictures** [comment] 2015-12-06 16:29
**ProdigyOG:** "The bypass is simply, really... All the client is doing is vclipping into the water, which allows the player to walk on the water.

Wrapper.getNetHandler().addToSendQueue(new C03PacketPlayer.C04PacketPlayerPosition(x, y - 1.722D, Wrapper.getPlayer().boundingBox.minY, z, true));
It's been more than a week since I posted this ticket... Do you guys want clarification/video?"

**Comment by MyPictures** [comment] 2015-12-06 16:29
**asofold:** "ProdigyOG:

No need for clarification, it is just not on a high priority.

While the current checks implementation is over-simplisitic and can be improved easily, waterwalk-like hacks are quite simple to make, and allow for "constantly" bypassing checks by implementing some "smart moving scheme".

We would be at a success, if we could detect most of "not just a good bot", open to discussion...

I assume we might ...

Extend set-back handling, probably with a per-player centralized manager-thing, to be able to have things like extra in-water and in-air set-backs, or even multiple of those, without having to add the priotitizing and managing code into the checks each time again.
Keep estimating water level and/or an average y-position.
Judge the moves above and below that, could count distances from there at some resolution and find too simplistic hacks by examining the counts, or how much players manage to stay close to a line.
Might need mixing with horizontal distances taken.
I don't know what you have in mind, but we need both to prevent false positives wth people who just use good timing with space bar, and to detect the most simple hacks. While this might get bypassed for "just water walk", it might already help killing water-sprint/speeding."

**Comment by MyPictures** [comment] 2015-12-06 16:29
**ProdigyOG:** "Another bypass: http://pastebin.com/yatrRt8Q"

**Comment by MyPictures** [comment] 2015-12-06 16:29
**FauraxMasterRace:** "Here the code to Jesus/WaterWalk: http://pastebin.com/LsdbfNGA"

**Comment by asofold** [comment] 2015-12-07 12:07
We will tackle speeding somewhat soonish, but we possibly won't start hunting dolphins, saints, nor any other type of fish/meaty.

**Comment by EvilOlaf** [comment] 2016-01-03 11:50
Confirmed. A player could walk on water like on conventional blocks.
Build 901 on Spigot 1.8.8
Unfortunately no debug log.

**Comment by asofold** [comment] 2016-01-03 12:01
@EvilOlaf We'd rather focus on speeding though :). Using the spacebar carefully one can also almost walk on/in water like on normal blocks, just slower.

**Comment by MyPictures** [comment] 2016-01-03 19:36
@asofold I think the speed is more a problem here then the high.

**Comment by asofold** [comment] 2016-01-03 20:48
Speed would be the other ticket then :). All speeding is meant to be treated there, because the methods to detect it will be much similar.

Detecting a specific Jesus hack or whatever it's named will be secondary, after we have remounted some more defenses against the generic stuff.

**Comment by CaptainObvious0** [comment] 2017-01-06 23:23
Any more updates on the progress of this check? 

I have been testing numerous Anti Cheats and AntiCheatReloaded caught my eye in terms of water walk. 

Source Code: https://github.com/Rammelkast/AntiCheatReloaded/blob/master/src/main/java/net/gravitydevelopment/anticheat/check/movement/WaterWalkCheck.java

I find this extremely effective against the "Jesus" hack. I'm not saying we simply copy and paste the code in, I'm saying that we could learn off of what it uses to block Jesus and adapt something similar to NoCheatPlus. I would be extremely happy if this check was adapted fully to SurvivalFly.

**Comment by asofold** [comment] 2017-01-08 15:42
There has been progress on cutting the possible speed slightly. I haven't received much information on how dolphin/water-related speeding turn out with the latest changes.

Concerning standing / walking on water, i don't see an effective limiting in the other anti cheating code, but i might've slipped past it. What i see is, speed limiting and something that might catch simple variants of walking above / on water.

The speeding part has much higher priority (...), as thats the really bad thing. Auto-moving/jumpinh including very short repeated jumping just inside of water are still possible anyway (bot-like). So if we tackle this, we must enforce the "real" physics of how deep the player has to dive in, how fluctuation may happen - possibly we end up with nothing much better than detecting specific implementations of cheats directly, and that would be too much work for too few gain (if we block standing on water, they'll be twitching on water or what not, so either we enforce the realistic envelope, or this'll be left for lots of future - or if anybody has a concise implementation or NCP that can be verified by third peoplef, a PR.).

**Comment by asofold** [comment] 2017-05-03 12:33
Closing as superseded, in favor of https://github.com/NoCheatPlus/Issues/issues/438 .

**Closed by asofold** 2017-05-03 12:33 UTC
Labels: (a) feature/enhancement, (c) cheat/bypass, (c.1) moving, (p.1) NoCheatPlus
