### ISSUE TITLE
Elytra flying 1.11.2

### ISSUE THREAD

**Issue by dwa1275** [NoCheatPlus/Issues#361] opened 2017-01-02 01:45 UTC
#### Short description of the issue.

when using rockets, lock in place or kicked for flying. when using elytra and hit water, kicked for flying

#### Complete output of the _ncp version_ command (please prefer text here).

latest dev build

#### How to reproduce the issue (is it random / always happens / side conditions)?

fly with elytra and use rocket, fly into water

#### Have you made any (noteworthy) changes to the default configuration of NCP?

set creative fly under moving to false will allow player to use rocket, but will still have random lag/stops in flight.

I'm not sure if hacked clients can cheat once disabled as I don't know what API is used in said clients

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

Ultra cousmetics - works fine except for blaze morph with uses same consept when flying (survivalfly slingshot effect) Kicked for floating to long in log but player does not get kicked

**Comment by Chnkr** [comment] 2017-01-02 12:20
Duplicate of #347

**Comment by asofold** [comment] 2017-01-08 16:21
Yes, please add news to the existing issue rather: https://github.com/NoCheatPlus/Issues/issues/347

**Closed by asofold** 2017-01-08 16:21 UTC
Labels: (r.2) duplicate
