### ISSUE TITLE
Can't jump since last spigot update

### ISSUE THREAD

**Issue by zenandreas** [NoCheatPlus/Issues#293] opened 2016-10-26 07:45 UTC
Few days ago we updated to the latest Spigot build and default players can't jump anymore.

**Comment by ultima84** [comment] 2016-10-28 05:38
I can confirm I am having the same issue on my server.
I updated spigot and the next day players NCP was kicking players for survivalfly, despite them only jumping.
I was getting NCP violation notifications, I disabled checking for survivalfly and creativefly and it produced the normal "<player> moved wrongly!" message.
I then went and updated NCP to the latest version and no change.
Is this caused by a change in spigot?

I downgraded spigot back to the version I was using prior to the issues and the issue is gone. It appears something changed in one of the last 8 spigot updates that is causing this issue.

**Comment by orkun1675** [comment] 2016-10-29 18:50
Having the same issue.

**Comment by asofold** [comment] 2016-11-01 00:07
Does this persist as of now (can't reproduce)?

**Comment by Platinteufel** [comment] 2016-11-01 00:10
https://github.com/PaperMC/Paper/issues/453

Fixed in the latest Paper builds. Haven't tested it with spigot yet.

**Comment by Platinteufel** [comment] 2016-11-01 00:30
Should no longer be relevant since spigot reverted this commit.

**Comment by ultima84** [comment] 2016-11-01 10:15
I updated to the latest spigot and NCP and am no longer having the issue.

**Closed** 2016-11-06 18:13 UTC
Labels: (r) superseded
