### ISSUE TITLE
Players sometimes get rolled back + falldamage when falling from high places

### ISSUE THREAD

**Issue by MithrandirCraft** [NoCheatPlus/Issues#68] opened 2016-01-02 13:47 UTC
Players sometimes get rolled back + falldamage when falling from high places.
This tipically happens when someone falls into the void, but it also may happen when players are simply falling from high places.

So, the player jumps from a high place, and before he takes any normal damage, he is teleported back to the original place, and the accumulated fall damage occurs.

This doesn't always happen, it happens occasionally so reproducing this may be a bit hard. The only additional thing I can say is that this issue has been present for a long time in various forms. I remember this happening with a 100% provability rate, and also happening with players dying in mid air due to fall damage long ago.

NCP Version: 3.13.4-BETA-sMD5NET-b901
Spigot Version: 1.8.8

**Comment by asofold** [comment] 2016-01-03 00:18
Can that be reproduced with build 909 or later (anyone)?

**Comment by MithrandirCraft** [comment] 2016-01-03 01:13
I can try this in 12h.

**Comment by asofold** [comment] 2016-01-20 10:16
Has this changed with build 914/920 in any way?

**Comment by MithrandirCraft** [comment] 2016-01-20 15:13
@asofold I applied your latest dev build. It's going to take some time untill I find any improvements/fixes.

In the meanwhile, I hope I don't find any new issues with these changes :P

**Comment by asofold** [comment] 2016-03-06 12:09
Some players (even with vanilla client) can somehow cause a set-back when falling to the void, though. At least it's been reported, that the somehow go to the settings screen while falling, possibly keeping mouse button pressed on window frame under windows ~ couldn't reproduce. I'd assume you'd have players suffer from that issue, who don't do such, though?

**Comment by MithrandirCraft** [comment] 2016-03-06 13:43
I know there's a very nasty hack that allows players to not fall into the void. Ideal for Skywars,

But I am not reporting that. I report a regular rollback without the use of hacks.

However, I think this issue has been diminshed, as I have not seen it produce recently.

**Comment by asofold** [comment] 2017-05-01 13:16
Closing as superseded, in favor of reports for current 'latest' combinations of server/plugins.

**Closed by asofold** 2017-05-01 13:16 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus, (q.2) IMPORTANT

**Comment by MithrandirCraft** [comment] 2017-05-01 13:40
what? ._.'

**Comment by asofold** [comment] 2017-05-01 13:44
Does the issue persist? :)

**Comment by MithrandirCraft** [comment] 2017-05-01 14:34
I haven't seen it no... However I have seen some rubberbanding during PVE, which is a different issue.
If I happen to notice anything in that regard I will report.
Now that I think of it, you are right on closing this ticket. No further comments.
