### ISSUE TITLE
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.

### ISSUE THREAD

**Issue by maxlehot1234** [NoCheatPlus/Issues#279] opened 2016-09-21 04:10 UTC
Hi, I use spigot 10.0.2 and latest nocheatplus dev version, but each time I join my server, I see:
http://pastebin.com/Hcrz1DYe

Is it normal?

I can't imagine with 100-200 players... Imagine the size of the logs :P

Thank you and if you have a fix or an idea, I will take it.

PS: I already contact: phenix (the dev that create forceressourcepacks on spigot) and he told me that it was not his plugin but yours.

**Comment by maxlehot1234** [comment] 2016-09-24 19:47
This is my version: http://pastebin.com/c1y1kA4w

**Comment by asofold** [comment] 2016-11-29 11:39
Sorry for the late reply:

com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:143) 


The exception appears to be from ProtocolLib or something related, not sure if it is fixed on their side, or if it is caused by plugins injecting stuff - the problem is that if they don't support the Player.getWorld method, they'll have a real problem with virtually all plugins breaking that ever use world-specific data. So no, it's not really on our side.

On the other hand we COULD do something to prevent the error and at the same time run our "net" group checks, however that'll be at the cost of efficiency for all users.

So i'm intersted to know... has this been resolved otherwise?

**Comment by asofold** [comment] 2017-04-19 15:12
Closing as superseded, assuming the issue not to remain on latest ProtocolLib + NCP.

**Closed by asofold** 2017-04-19 15:12 UTC
Labels: (a) issue/task, (c) other, (p) compat/external, (p.1) NoCheatPlus
