### ISSUE TITLE
Question regarding moving players with pistons

### ISSUE THREAD

**Issue by James76931** [NoCheatPlus/Issues#287] opened 2016-10-17 19:01 UTC
Hi,

I was wondering if there is a specifically permission to allow players to be moved by pistons as some people would like to make lifts in their houses.

Thanks,
_\- James_

**Comment by James76931** [comment] 2016-10-26 22:08
Could I have a response soon please?

**Comment by Janmm14** [comment] 2016-10-30 00:12
asofold and development around NoCheatPlus is pretty much quiet, so there won't be a response probably

**Comment by asofold** [comment] 2016-10-31 23:31
Piston support is near 0 right now. I have experimented with some piston support infrastructure, and it still is a hot topic.

Thus there is no permission to do it in a simple way. In short, we deal with latency towards the client, which varies wildly over time and amongst players, so we have to account for players probably having been on ground due to pistons or passing through blocks that have just been placed there by pistons, in addition to the sudden moving caused by bying pushed. Technically possible, but potentially complicated to work into the code base.

**Comment by Janmm14** [comment] 2016-10-31 23:39
Pistons could also pull players (go into the piston if its out and when it retracts it pull you and piston could move block attacked with slime blocks and smae has to be handled for them.

**Comment by asofold** [comment] 2016-11-01 00:30
Right, pulling works as well. For tracking, this isn't such a big difference, since we get told the direction and the blocks, regardless of pushing vs. pulling. Of course the technical issues with removed/placed ground and moving through blocks essentially remain the same.

**Comment by asofold** [comment] 2016-11-05 21:48
Closing as duplicate:, please upvote this / continue here: https://github.com/NoCheatPlus/Issues/issues/5

**Closed** 2016-11-05 21:48 UTC
Labels: (r.2) duplicate
