### ISSUE TITLE
nocheatplus.checks not properly working?

### ISSUE THREAD

**Issue by Theepwner** [NoCheatPlus/Issues#284] opened 2016-10-07 05:26 UTC
I've given nocheatplus.checks to all users in a certain world, but there are still reports of lag-backs, and still feels like some nocheatplus checks are in effect.

Am I missing something?

**Comment by asofold** [comment] 2016-10-08 22:16
Not all lag-back need to be due to NoCheatPlus...

There are some things that don't have a permission check with it (not sure right now which exactly, possibly placing blocks vs. water and such). Typically blocks and moving should be fully exempted from with permissions.

If you are using ProtocolLib as well, it could in theory be a bug with permissions not being updated/checked for protocollib based checks (rather extreme packet spamming, but thinkable to trigger with networking congestion). Are there any violation alerts for that world?

'ncp info PLAYERNAME' could show checks triggering, however one would need to test the difference to the point of time of them entering the world, which probably isn't a 100% practicable thing to do, unless they can for sure reproduce issues.

**Comment by Theepwner** [comment] 2016-10-08 22:50
I've added this perm to users as well: nocheatplus.shortcut.bypass

and don't seem to be experiencing anymore lag-backs.

**Comment by Theepwner** [comment] 2016-10-10 10:00
I'm guessing these lag-backs might be related to our custom knockback plugin that isn't quite vanilla knockback mechanics? If so, what would be the solution?

**Comment by asofold** [comment] 2016-11-05 21:59
If permissions don't work it would be a problem.

Could you post the complete output of the 'ncp version' command? It's really important to know what we are dealing with here ...

Also please include your permissions plugin (+ version), as that could in theory be related.

Custom knockback could pose trobule, though just adding velocity would be intended to be compatible (...), what does it do?

**Comment by asofold** [comment] 2017-05-02 20:44
Closing as 'superseded' - please drop a note if it's still an issue (or needs more confinement / such) - in general debug logs are the best to resolve special features.

**Closed by asofold** 2017-05-02 20:44 UTC
