### ISSUE TITLE
End Portals & survivalfly

### ISSUE THREAD

**Issue by hurrgurl** [NoCheatPlus/Issues#262] opened 2016-08-09 03:15 UTC
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1022

**Jumping** to end portal generates survivalfly VL 5000-7000 - results in a kick with newly generated config.

After kick and relogin player is teleported to 0 0 0 instead of the right location, as tho Minecraft doesn't know where to spawn them.

**Slowly walking** into end portal works as intended, no false positives.

**Comment by MarkElf** [comment] 2016-08-09 13:37
Duplicate of #221 .

**Comment by MyPictures** [comment] 2016-09-08 20:44
Closed because of duplicate.

**Closed by MyPictures** 2016-09-08 20:44 UTC
