### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Xayanix** [NoCheatPlus/Issues#408] opened 2017-04-10 13:30 UTC
#### Short description of the issue.
Just error in console. Players are reporting that they're unable to enchant items (not sure if its related with this issue).

#### Complete output of the _ncp version_ command (please prefer text here).
http://scr.hu/0duk/fllig

#### How to reproduce the issue (is it random / always happens / side conditions)?
random

#### Have you made any (noteworthy) changes to the default configuration of NCP?
no

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
no

[15:22:36] [Craft Scheduler Thread - 1341/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for INVENTORY_OPEN (see earlier log with id=-1611701050).
[15:22:36] [Craft Scheduler Thread - 1341/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for INVENTORY_OPEN (see earlier log with id=-1611701050).
[15:22:38] [Craft Scheduler Thread - 1359/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for INVENTORY_OPEN (see earlier log with id=-1611701050).
[15:22:38] [Craft Scheduler Thread - 1359/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for INVENTORY_OPEN (see earlier log with id=-1611701050).

**Comment by asofold** [comment] 2017-04-10 16:12
The error means that another plugin is causing an event to fire outside of the usual thread-context, be it intentional or not (some things induce further actions, e.g. teleport events could follow exiting vehicles and vice versa). The reason why NCP is warning there, is that this can cause severe issues, due to most plugins (including NCP) not being prepared for standard events like BlockBreak or PlayerTeleport firing from another thread than the primary server thread. Adapting to the possibility of every event firing from any thread isn't feasible and not even possible, because lots of the Bukkit API simply is not thread-safe and can only be accessed from within the primary thread. 

That being said, you'll probably want to find out which plugin is involved in doing what (assuming it's not a bug in NCP): In the log there should be another message with _id=-1611701050_ in it, stating a stack trace of when this happened first. Could you find and post that for reference?

**Comment by asofold** [comment] 2017-04-19 14:19
The above hint will lead to identifying the plugin that is causing the events to fire outside of the typical thread context - i'll  close this as ... can't fix, assuming it's not caused by a newly introduced bug in NCP.

**Closed by asofold** 2017-04-19 14:19 UTC
Labels: (a) issue/task, (c) other, (p) compat/external, (p.1) NoCheatPlus
