### ISSUE TITLE
AoE damage with swords since mc 1.9

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#180] opened 2016-05-18 15:58 UTC
Since 1.9 you can hit multiple mobs with one punch (AoE damage), but it seems like my users are not able to use this new features. For my OPs it works fine. Maybe NCP blocks it?

**Comment by asofold** [comment] 2016-05-21 14:53
Which version of NCP is used? What's the server version? 

Here  it really matters what is running on that instance, also/especially if it's a pre-1.9 server with 1.9-protocol support.

**Comment by Platinteufel** [comment] 2016-05-21 15:15
[17:15:20 INFO]: ---- Version information ----
[17:15:20 INFO]: #### Server ####
[17:15:20 INFO]: git-Paper-724 ~MC: 1.9.2~
[17:15:20 INFO]:   detected: 1.9.2
[17:15:20 INFO]: #### NoCheatPlus ####
[17:15:20 INFO]: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b973
[17:15:20 INFO]: MCAccess: 1.9-1.9.3 / Spigot-CB-1.9_R1
[17:15:20 INFO]: Features:
[17:15:20 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
[17:15:20 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[17:15:20 INFO]:   defaults: pvpKnockBackVelocity
[17:15:20 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
[17:15:20 INFO]: Hooks: AllViolations~NCP~ 1.0
[17:15:20 INFO]: #### Related Plugins ####
[17:15:20 INFO]: ProtocolLib v4.0.0-b280

**Comment by asofold** [comment] 2016-05-22 09:46
In general the sweep attack should be supported, however it currently is a hacky workaround for detecting that kind of damage and it could break with changes to client/server or with plugins changing the damage of the area damage events before NCP receives them.

I'll adjust something to test those vs. the original damage amount to exclude other plugins on EventPriority.LOWEST interfering - this needn't be the reason for issues, though.

Do players actually receive violations for such cases? If you have few people on, you could test this with adding the _debug: true_  to the checks.fight section of the configuration, in order to only activate debug logging for fight (much less than for moving).

**Comment by Platinteufel** [comment] 2016-05-23 18:06
![ncp bug](https://cloud.githubusercontent.com/assets/13700636/15479711/c5d0914e-2121-11e6-80d1-53782ca1ce9c.png)

Violations in a xpfarm with a lot of mobs at one place (AoE dmg blocked due to ncp)

**Comment by asofold** [comment] 2016-05-23 20:28
Can't reproduce, are you able to trigger those violations always or at will?

Are plugins involved that change damage?

If you can reproduce it systematically, could you reproduce it with checks.fight.debug set to true in the configuration (needs to be manually added)?

**Comment by Platinteufel** [comment] 2016-05-24 12:39
Always. Here's a short video, tested on a sandbox server (only ncp and pex installed). As you can see, my sword does AoE damage when I'm OP, otherwise I keep getting violations and my AoE damage is blocked. Please tell me if you need more debug logs. 
https://youtu.be/6DMAyJHbL-g

**Comment by asofold** [comment] 2016-05-24 16:41
The log looks like the debug flag for the checks.fight  section had not been set - is it possible to run it with that added (_debug: true_  <- only at checks: ... fight: debug: true)?

If too many players are on, you could also set  _logging.extended.allviolations.backend.trace: true_
I forgot right now if that will also log damage amount on violations but it'll show all violations of all players, which can be less than all fighting logging.

(After reproducing a couple of times, don't forget to remove the flag/setting and _/ncp reload_ . Before testing, ensure to have it active with _/ncp reload_, perhaps.)

**Comment by Platinteufel** [comment] 2016-05-24 22:01
Sure. :) Same situation like in the video with debug logs: http://pastebin.com/Ji53JisU

**Comment by asofold** [comment] 2016-05-25 07:26
This log looks like the sweep attack is registering correctly as such. If this is the same setup as the others, perhaps there are other side conditions (skill/penalty-skill implementation) or it's just not related to AoE. If you had a log where it also triggers violations... but that really needs reproducing the cancelling...

I assume that there doesn't exist AoE damage for an already cancelled event, otherwise we would have to detect such, it certainly would show in the log.

**Comment by Platinteufel** [comment] 2016-05-27 18:03
I'm not sure what you need. But I can tell you that if I debug 'fight' with 'fight: debug: true' I can deal AoE damage without problems, maybe because it doesn't cancle events in debug mode? Here's another debug log, tested right now, but it's nearly the same like 3 days before: http://pastebin.com/9HR94pLE

**Comment by asofold** [comment] 2016-05-29 18:24
Very unlikely that debug mode changes anything there, would be very surprising. Is it that easy to reproduce the issue without debug logging on?

**Comment by Platinteufel** [comment] 2016-05-29 20:59
Hm? The posted video should explain the issue - debug mode is out there.
https://youtu.be/6DMAyJHbL-g

**Comment by asofold** [comment] 2016-05-30 07:42
I understand the issue from the video, i understand the debug log. I don't know how the client and server states get desynced...
* Cheating? [Unless 100% confirmed'n'trusted never-trolling super heroes, one always has to account for such possibilities, even if assume this not to be cheating/trolling, and i did forget what the player name in the video was, so excuse me if it was you :p]
* Client somehow forgot to tell the server it's not blocking anymore, or the server somehow forgot that the client sent it.
* The client itself has a faulty method of setting the blocking state, e.g. moving like not blocking, but sending 'i'_m blocking' to the server on processing the tick, e.g. because they had been blocking during that tick. If such is related to client-side lag or other odd circumstances like plugins forcing the player state to change, is another question.

Now the question i have for you, would be if it can be easily reproduced - can someone do this at will, or is it a very rare thing to happen?

**Comment by Platinteufel** [comment] 2016-05-30 08:26
I have a pucblic xp-farm where ppl can kill mobs like in the video. ALL my players are telling me that it is not fair that staff members (with op) are able to deal AoE damage here and can kill the mobs much faster like the "normal" players. So .. I would say it's not a very rare case if I get 2-3 reports everyday. :p
AoE damage is new since 1.9, in earlier versions ( <= 1.8) it wasn't possible to hit more than 1 mob with 1 hit. I don't know how this checks are exactly working, but I would say NCP thinks the player is cheating since the AoE damage wasn't possible till now.

**Comment by Platinteufel** [comment] 2016-05-30 08:32
And the player in the video was me, I always test issues on a sandbox server before reporting them. ;)

**Comment by asofold** [comment] 2016-05-30 20:35
@Platinteufel Oh great!

Well NCP has a detection for the follow-up damage built in, which can be seen in the debug log.

So either you didn't manage to reproduce the issue on the sandbox server, e.g. due to not having enough latency, or some different plugin (~ setting?), OR debug logging changes the fight checks. The latter i find quite improbable, but perhaps i should have a look if this could in theory be the case, i'd assume _latency_ or perhaps different plugins/settings.

**Comment by asofold** [comment] 2016-05-30 20:57
So thanks a lot, this was _very important_, and yes: sweep attack detection would only work with debug on.

That's a problem, if all the hundreds of QA people all test with debug logging on :p - funny though, that there have been so few reports, regarding that sweep attack detection has been effectively turned off for production.

Note that the latest build should fix THAT issue, but it contains a range of actually [BLEEDING] changes, that are not marked as such (sorry). It would be very rewarding if this could be tested by someone - the changes concern the fight checks mostly for pvp ith reach and direction. Only internals have been changed, so question is if something blows up / memory leaks / endless loops, the usual!

**Comment by Platinteufel** [comment] 2016-05-30 23:38
Oh okay, I was wondering why debug logging changes anything on this point. :D

Thanks, AoE damage works perfectly for me with the latest build on my testserver. I hope you forgive me that I'm not interested in installing experimental builds on my main server, so I will come back after a few (stress-)tests on my testserver. But thank you so far!

**Comment by asofold** [comment] 2016-05-31 04:52
That's great. There are some unit tests for the changed parts, so it's probably not as risky as it could be, but it's certainly better to throw it on a server with a couple of players on for testing, for a while.

**Comment by Platinteufel** [comment] 2016-06-05 19:35
No problems so far, I think you can close this. :)

**Comment by asofold** [comment] 2016-06-05 21:41
Thanks, will go for one or two fixes and release then.

**Closed by asofold** 2016-06-05 21:41 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus
