### ISSUE TITLE
Kicked whilst joining for SurvivalFly

### ISSUE THREAD

**Issue by Brushes** [NoCheatPlus/Issues#91] opened 2016-02-15 11:51 UTC
Hi,

We have an issue on our server where players get kicked when the join for "SurvivalFly".

I have looked everywhere and have found no luck, I do not wish to disable SurvivalFly completely either.

Please help!

Thanks.

**Comment by asofold** [comment] 2016-02-16 11:43
Please always post the full text output of the 'ncp version' command. We need that information to judge what to ask next...

**Comment by Brushes** [comment] 2016-02-16 12:10
16.02 07:07:02 [Server] INFO ---- Version information ----
16.02 07:07:02 [Server] INFO #### Server ####
16.02 07:07:02 [Server] INFO git-Spigot-db6de12-3f3c65f ~MC: 1.8.8~
16.02 07:07:02 [Server] INFO detected: 1.8.8
16.02 07:07:02 [Server] INFO #### NoCheatPlus ####
16.02 07:07:02 [Server] INFO Plugin: 3.13.7-RC-sMD5NET-b925
16.02 07:07:02 [Server] INFO MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
16.02 07:07:02 [Server] INFO Features:
16.02 07:07:02 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
16.02 07:07:02 [Server] INFO checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
16.02 07:07:02 [Server] INFO defaults: pvpKnockBackVelocity
16.02 07:07:02 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
16.02 07:07:02 [Server] INFO Hooks: AllViolations~NCP~ 1.0
16.02 07:07:02 [Server] INFO #### Related Plugins ####
16.02 07:07:02 [Server] INFO ProtocolLib v3.6.4




Also please note I have survivalfly disabled at this current time so it would let people join.

**Comment by Platinteufel** [comment] 2016-02-16 14:12
Do you have an authentication plugin like AuthMe?

**Comment by Brushes** [comment] 2016-02-16 22:16
Nope.

**Comment by Brushes** [comment] 2016-02-16 22:17
Pretty much the only Auth thing we have is the online mode.

**Comment by asofold** [comment] 2016-02-18 09:20
So we need to elaborate...
* Does it happen to all players all the time? If not how often/many players?
* Can side conditions be confined to something (log in on stairs / water / air, already stuck before logout, after server restart, always with having played after last restart. such ...)?
* Could you post violation messages up to a kick?

**Comment by Brushes** [comment] 2016-02-18 13:39
- Yes it happens to every player (except for ops)
- Don't really understand what you mean, but it happens at any place.
16-02-15 06:23:02 [INFO] Karbzee failed SurvivalFly: tried to move from 14.67, 30.00, 7.00 to 8.50, 65.00, 8.50 over a distance of 35.57 block(s). VL 4064.
16-02-15 06:23:09 [INFO] Karbzee failed SurvivalFly: tried to move from 14.67, 30.00, 7.00 to 8.50, 65.00, 8.50 over a distance of 35.57 block(s). VL 8127.
16-02-15 03:41:57 [INFO] Karbzee failed SurvivalFly: tried to move unexpectedly. VL 138.
Them errors vary in the information that it gives off every kick^ I picked on that player specifically because that is the player I tested it with.

- Couldnt find the exact login location in bukkit.yml

- Not that I know of.

**Comment by asofold** [comment] 2016-02-18 23:21
@Brushes The violations cover a long distance, too long to be an ordinary false positive.

The setting use-exact-login-location is in bukkit.yml. Does it change if you set use-exact-login-location to true, in case it is set to false right now? The effect might be that players can spawn inside of blocks, if those blocks got placed after their logout.

Apart from that a debug log could be helpful (e.g. 'ncp debug player Karbzee', reproduce the issue a couple of times, after reproducing 'ncp remover Karbzee', results in the log file of NCP).

**Comment by Brushes** [comment] 2016-02-18 23:49
Here is the debug information, I got Karbzee to stand on the ground and log in and out, this is what the log told me.
http://pastebin.com/MNneS6CT

Also, I still cant find what you are telling me to look for in bukkit.yml, this is what our bukkit.yml looks like: http://pastebin.com/G7mi07Q5

**Comment by asofold** [comment] 2016-02-18 23:55
@Brushes Perhaps exact login has been removed.

Did you teleport to locationfrom and locationto to cross check?

The violations look very odd overall, i assume there is something odd going on.
* Are you sure the player is using a vanilla client?
* Could you send us a plugin list (either post here, or pm on dev.bukkit.org or spigotmc.org)?

**Comment by Brushes** [comment] 2016-02-19 01:32
We tried this in many different locations, still the same result. It happens anywhere on the server.

Karbzee is running 1.8.8 Client

I forgot to attach the plugin list sorry, here: http://imgur.com/e4syJg5

**Comment by asofold** [comment] 2016-02-21 00:15
Looks like some plugin is interfering in a problematic way, or the player is cheating.

**Comment by Brushes** [comment] 2016-02-22 22:58
Hi,
Do you mean that you will look into the log with more detail?

I will debug the player again when I get the chance and will send it over to you.

**Comment by Brushes** [comment] 2016-02-22 22:58
One of the biggest problems though is when a player logs off whilst they are flying, and when they log back in it kicks them.

**Comment by Platinteufel** [comment] 2016-02-23 00:55
Not directly a ncp problem, just give them essentials.fly.safelogin ;)

**Comment by Brushes** [comment] 2016-02-23 01:52
I think it is because it comes up the Failed SurvivalFly then it kicks the player.

**Comment by Platinteufel** [comment] 2016-02-23 03:26
As I said, give them the essentials.fly.safelogin permission and you will get rid of this problem.

**Comment by Brushes** [comment] 2016-02-23 10:21
Hi,

This didnt fix the problem.

But I was able to track down exactly when it happens.

Looks like I was wrong, it only happens if the player logs out on a slab or stairs. Even though it says the player tried to move like 30 blocks, they are only spawning on a slab.

Any ideas?

**Comment by asofold** [comment] 2016-02-23 22:03
So they go up 30 blocks after logging out on slabs...

Did you check the location they tried to move to, just a random 30-blocks-above one from the linked logs? Could be interesting to know what's there.

**Comment by asofold** [comment] 2016-06-15 11:07
Assume superseded by ncp and/or server changes - please add a comment or open a new issue if similar issues persist.

**Comment by Brushes** [comment] 2016-06-16 12:24
Hi,

I forgot that I had posted this, sorry! What does the superseded stand for btw?

I am also still having this issue with the kicking of SurvivalFly. It's very annoying.

**Comment by asofold** [comment] 2016-06-16 16:57
I use superseded for something like  'either plugin and/or server made too many related changes since ...'. So the side conditions for this have changed, and it needs to be reevaluated at least.

Which build are you on?

**Comment by asofold** [comment] 2017-05-01 12:30
Closing as superseded :p - many things have changed, would need another try with build 1084 or build 1090.

**Closed by asofold** 2017-05-01 12:30 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus, (r) superseded
