### ISSUE TITLE
Issue / Suggestion

### ISSUE THREAD

**Issue by Xayanix** [NoCheatPlus/Issues#360] opened 2017-01-01 21:24 UTC
Hi.

As you know, NoCheatPlus does teleport player back on detection of flight. You can abuse this method to get teleported back (for example in Parkour servers). Video: https://www.youtube.com/watch?v=VwPol1O01j4&feature=youtu.be

My solution is teleporting player to the ground (first block under him) with fall damage calculation. Answer if you agree with me.

**Comment by Chnkr** [comment] 2017-01-02 12:20
Duplicate of #348

**Closed** 2017-01-02 14:41 UTC
