### ISSUE TITLE
Skillclient bypasses many NCP-Features

### ISSUE THREAD

**Issue by Sprungente** [NoCheatPlus/Issues#381] opened 2017-02-11 16:39 UTC
#### Short description of the issue.

Skillclient (https://skillclient.tk/ ) will bypasses many NCP Features. for example

- [ ] Walk over water (Jesus)
- [ ] Fast Break
- [ ] Fast Place
- [ ] Freeze in the air with elytra
- [ ] Wall hack (To see through walls)
- [ ] Chestesp (See chest through all)
- [ ] Tracer and Nametag (Maybe is possible to block it?)
- [ ] Tower (Build it with fake blocks in the air)
- [ ] Flying with boats 
- [ ] NoFall 
- [ ] Chestaura (Open cheat out of reach)
- [ ] Killaura 
- [ ] Chestloop (put all items in the chest maybe possible to block this?)
- [ ] BlockBuild (automatically very fast build )
- [ ] bowboost (partially blocks but it works)
- [ ] Bowaimbot (works complettly maybe it possible to block it?)
- [ ] autohealpotion (Throw healpotion without use it and isn't in off or main hand)
- [ ] Bettersneak (Fast + Auto sneak )
- [ ] AntiKnockback 
- [ ] FastUse (Fast Eat, fast bow loading)
- [ ] Bedfucker (same as chestesp only with beds)

#### Complete output of the _ncp version_ command (please prefer text here).

`11.02 16:35:12 [Server] INFO ---- Version information ----
11.02 16:35:12 [Server] INFO #### Server ####
11.02 16:35:12 [Server] INFO git-Spigot-b4417b8-a1d3777 ~MC: 1.11.2~
11.02 16:35:12 [Server] INFO detected: 1.11.2
11.02 16:35:12 [Server] INFO #### NoCheatPlus ####
11.02 16:35:12 [Server] INFO Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1064
11.02 16:35:12 [Server] INFO MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
11.02 16:35:12 [Server] INFO Features:
11.02 16:35:12 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
11.02 16:35:12 [Server] INFO checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
11.02 16:35:12 [Server] INFO defaults: pvpKnockBackVelocity
11.02 16:35:12 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
11.02 16:35:12 [Server] INFO Hooks: AllViolations~NCP~ 1.0 | Citizens2~cncp~ 2.0 | mcMMO~cncp~ 2.3 | MyPet 1.0
11.02 16:35:12 [Server] INFO #### Related Plugins ####
11.02 16:35:12 [Server] INFO CompatNoCheatPlus v6.6.3-SNAPSHOT-sMD5NET-b87 | ProtocolLib v4.2.0`

`11.02 16:36:07 [Server] INFO This server is running CraftBukkit version git-Spigot-b4417b8-a1d3777 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`

#### How to reproduce the issue (is it random / always happens / side conditions)?
Every , i tested it with a friend

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No -- Default config

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
SimpleBroadcast, BungeePerms, RisingSystem, OldCombatMechanics, SuperTrails, VoxelSniper, RewardVoting, LiveSupportChat, Commandspy, AsyncWorldEditInjector, CoreProtect, dynmap, WorldEdit, Rising-Umfrage, OnlyProxyJoin, NBTEditor, Chairs, Votifier, TablistPrefix, Multiverse-Core, ProtocolLib, IPWhitelist, BlocksHub, mcMMO, Multiverse-Portals, Vault, LWC, HolographicDisplays, WorldGuard, BungeePortals, MysqlEconomyBank, BungeeTabListPlus, AreaShop, Essentials, Jobs, Paintball, 1vs1, Citizens, AsyncWorldEdit, AdvancedAchievements, EssentialsChat, ItemCases, Sentries, ChestShop, Quests, EssentialsGeoIP, EssentialsSpawn, CompatNoCheatPlus, NoCheatPlus, EditableSign, ServerSigns, MyPet, MyPet-NPC

All our plugins 

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
---

I hope you use this as a checklist/to do list and fix it (or many of them) in the next time and I hope I can help you and help the safety of many Minecraftservers.

**Comment by jonesdj1** [comment] 2017-02-11 20:30
you can not fix lots of these anything that renders stuff cant be fixed

**Comment by Sprungente** [comment] 2017-02-11 20:34
yes i thought it

But some things could be fixed or improve, that I will to reach with this issue

**Comment by jonesdj1** [comment] 2017-02-11 22:33
alot of this is fixed if you use 1.9+ on latest dev build stuff like fastuse does not work also flying with boats is patched

**Comment by Sprungente** [comment] 2017-02-12 02:17
should...  but b1064 is the newest build and it isn't blocked. Maybe the creator from this client has found many gaps

**Comment by jonesdj1** [comment] 2017-02-12 10:53
@Sprungente well if your op everything should work

**Comment by Sprungente** [comment] 2017-02-12 16:54
We tested it without OP or something

**Comment by jonesdj1** [comment] 2017-02-12 17:22
@Sprungente is your server version 1.9 or higher if your server is 1.8 it is just client sided as its patched 100%

**Comment by Sprungente** [comment] 2017-02-12 17:23
INFO This server is running CraftBukkit version git-Spigot-b4417b8-a1d3777 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by jonesdj1** [comment] 2017-02-12 18:38
@Sprungente Just testing everything and Boatfly, FastUse, Jesus, Fast Break, NoFall, Killaura(sorta flagged some times) did not did not test everything but everything really did not work will post the video when its done uploading.

**Comment by jonesdj1** [comment] 2017-02-12 18:40
https://www.youtube.com/watch?v=wgY-WxSIa7Q

**Comment by Sprungente** [comment] 2017-02-16 07:42
Do you tested it wit compatnocheatplus?

**Comment by jonesdj1** [comment] 2017-02-16 12:27
@Sprungente compatnocheatplus should not make a difference

**Comment by asofold** [comment] 2017-02-17 22:31
For block breaking speed mcMMO could make a difference - in case of changes on mcMMO side, it could also happen that players get exempted from more attack/block-break events than intended (in theory).

For such a list, we need to categorize things more, it's also necessary to estimate the gain from using a cheat, compared to what a vanilla client can do (with the exception of obvious things like flying, perhaps). E.g. If tower just works like an auto building thing (bot), or "just" wins 5-10% time, it'll not be of such importance. If you can do 5-10 blocks instantly (tower), and then get blocked, perhaps it's not extreme, but it may be possible to tackle somehow. The other thing is that there are existing tickets :) for some aspects.

I don't know if it's a trust thing with not debug logging such or if it's a production server - sometimes people wouldn't show off their cheats, if they know it's being recorded. If it's possible to reproduce on a test server, debug logs could really help (zip and upload here), in such a case with checks.debug set to true and ProtocolLib on.

I would further ask for:
* Flying with boats
* NoFall [Really? For 3 blocks height or for any height / how / when does it work, when not?]
* Chestaura (Open cheat out of reach) [through walls ?]
* autohealpotion (Throw healpotion without use it and isn't in off or main hand)  ['without use' ?]

Some things are client side, and possibly could be detected, typically at a greater performance impact, and you'll rather catch the careless people for things like tracers. For some things tickets already exist.

For things like tracers one would need to identify players moving towards other players/chests/similar, and then judge if it's been possible to spot, or probably to happen or just a random outlier. It could be something not so simple to detect, like a block placed somewhere you can see from far, and the block is not typical for that biome/position, or more subtle, it could be blocks removed in a way, that can't result from ordinary terrain generation - how is such supposed to be tracked by a plugin (best without much impact on performance). We could attempt to create abstractions for behavior of players and use those as inputs for some machine learning thing, but really that's a research task that takes a lot of time, and it'll still take lots of time to maintain and likely not lead anywhere better than catching the more careless kind of thieves (in reality usually people who don't have any resources and who are not trained, possibly they're already starving). It could become interesting, if we use (higher bandwidth) database connections for storing a lot of behavioural abstractions and sequences of things, so checks can be run 'offline' as well - such is more complex on implementation side and also for takes more time to reasearch and then to maintain (...).

**Comment by v0idst4r** [comment] 2017-02-20 08:54
@asofold Perhaps some check that makes the player have to hold an item for a certain amount of ticks before being able to use it? It'd semi patch autopotion/soup, or it'd make it weaker

**Comment by v0idst4r** [comment] 2017-02-20 08:55
I doubt skill client has a no fall for 1.8 laest NCP, unless it's a reconnect one which was unpatched when you patched fake fall damage

**Comment by v0idst4r** [comment] 2017-02-20 08:58
And @Sprungente auto potion works by silently sending a HeldItemChange packet, using the item, then sending a packet back to the current item

**Comment by v0idst4r** [comment] 2017-02-20 08:58
So technically it's in the players hand but for less than a tick

**Comment by jonesdj1** [comment] 2017-02-20 23:40
@v0idst4r 

> @asofold Perhaps some check that makes the player have to hold an item for a certain amount of ticks before being able to use it? It'd semi patch autopotion/soup, or it'd make it weaker

that would be horrible for players to use potions and causing pots to simulate lag not like potions are used anymore in pvp really food is way better over potions in 1.9+

**Comment by v0idst4r** [comment] 2017-02-20 23:44
It'd only cause "pots to simulate lag" if for some reason you're hotkeying and right clicking within 100 milliseconds which isn't humanly possible

**Comment by jonesdj1** [comment] 2017-02-20 23:48
@v0idst4r I thought you where saying like 1 second plus delays and like everyone hotkeys and right clicks in potion pvp

**Comment by v0idst4r** [comment] 2017-02-21 01:24
Yeah but with at least a 3 tick delay, auto soup and auto potions instantly
do it

new CPacketHeldItemChange(potionSlot);
new CPacketTryUseItem(EnumHand.MAIN_HAND);
new CPacketHeldItemChange(oldSlot);

Something along the lines of that, I've never seen a single autopotion or
autosoup have a delay between changing items and using them

**Comment by asofold** [comment] 2017-02-21 17:31
Well, there can be lag  (networkling congestion, delay, client-side, server side (!) ...), so you'll hardly be able to prevent just one time, you'll have to monitor things for a while - and that may be the end of the fight already.

Of course you can cross check with other packets and estimate if some "instant related packets"  have a good reason to be instant. This is quite interesting, but also potentially complex.

Cheat clients will also become better at cloaking things somehow, perhaps they can fake some evasive move, estimate the probability of getting hit again within short time etc., but first they'll consider adapting to whatever we do on this account. E.g. if we can only nail it down to few ticks, perhaps they'll just have it take few ticks then. A pro can switch the item during jumping easily i guess, and using it afterwards should be simple too, so what can we do concerning instantly consumable items, if it's  meant to provide some kind of protection for a little longer time...

**Comment by MCmodding4K** [comment] 2017-04-15 22:00
funny xD

**Comment by asofold** [comment] 2017-04-19 14:31
Since i currently can't test clients myself, i'll close this ticket - in favor of specific reports for stuff that hurts most. Fastest fixes are with debug logs (not always possible due to trust-issues :p), for judging severity of speeding consider the 'ncp stopwatch distance 100' command for comparison (or 50, if you don't have enough time to build a flat thing). Please prefer testing with the latest / late-ish builds.

Apart from fixing easy to as well as rather critical issues, upcoming changes can be seen here: https://github.com/NoCheatPlus/Docs/wiki/Roadmap

**Closed by asofold** 2017-04-19 14:31 UTC
