### ISSUE TITLE
Better Block Interact Direction check

### ISSUE THREAD

**Issue by CaptainObvious0** [NoCheatPlus/Issues#371] opened 2017-01-21 00:53 UTC
#### Short description of the issue.
Breaking/Interacting with blocks that have little break time will cause the BlockInteract direction check to trigger.

#### Complete output of the _ncp version_ command (please prefer text here).
[18:52:57 INFO]: ---- Version information ----
[18:52:57 INFO]: #### Server ####
[18:52:57 INFO]: git-Spigot-7d78b81-f709362 ~MC: 1.11.2~
[18:52:57 INFO]:   detected: 1.11.2
[18:52:57 INFO]: #### NoCheatPlus ####
[18:52:57 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1054
[18:52:57 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[18:52:57 INFO]: Features:
[18:52:57 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
[18:52:57 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[18:52:57 INFO]:   defaults: pvpKnockBackVelocity
[18:52:57 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[18:52:57 INFO]: Hooks: AllViolations~NCP~ 1.0
[18:52:57 INFO]: #### Related Plugins ####
[18:52:57 INFO]: ProtocolLib v4.2.0

#### How to reproduce the issue (is it random / always happens / side conditions)?
Breaking blocks with little break time while moving fast will cause the block interact check to trigger.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No changes that would effect the check.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
None

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

Small portion of ncp debug: http://pastebin.com/58v15zRu

Proposal on how to fix the issue: (1) Add a list to the end of the config that a user can add blocks that will be ignored by block interact, or (2) Add a config value to the block interact direction check that will be set to a decimal, and block breaks under that time will be ignored. 
Ex. breaktime: 1  # Blocks that are broken under a time of one milliseconds will be ignored by the check.

**Comment by asofold** [comment] 2017-01-22 19:49
Such/similar configuration options probably make sense.

I'd assume this is caused by out of order processing of events, which is what the server is doing to us for moving/look vs. interaction on occasion :(.

We do scan past packets for potential matches (for blockinteract), not sure this is really that thing. It would be best to debug log this on a test server with protocollib, having checks.debug set to true (preferred over on the fly debug logging, though that would good to start with as well).

**Comment by Xayanix** [comment] 2017-01-26 22:01
This issue is real. When i have iron pickaxe with efficiency 5, then i got a lot of false positives. This should be fixed ASAP.

**Comment by asofold** [comment] 2017-04-30 18:01
This should be fixed by now, if you use ProtocolLib (assume packet order inversion).

The issue will now be the blockbreak.direction check until fixed as well (...).

**Closed** 2017-04-30 18:01 UTC
