### ISSUE TITLE
1.9: NCP build 936 vs Build 9​37

### ISSUE THREAD

**Issue by partydragen** [NoCheatPlus/Issues#111] opened 2016-03-06 00:00 UTC
1.9 Bugs with build 9​37

* When them goes on Purpur Stairs them get kicked for flying
* the new 1,8 doors are from North or South them can not go through only work with wooden door

Edited by staff: Already known:
* Can not use elytra
* Skulker effect kicked for flying

**Comment by MyPictures** [comment] 2016-03-06 09:19
Please provide a /ncp version in your ticket so we can setup an environment that matches yours (Spigot version is also important).
Some of your points are a duplicate of this tickets: https://github.com/NoCheatPlus/Issues/issues/56

Thank you for the report.

**Comment by asofold** [comment] 2016-03-06 11:50
First we/you need to ensure not to run a too old version of Spigot (!) - please ensure it's about the latest, because the initial versions had an inconsistency/bug that would render current NCP builds incompatible.

The interesting point would be if stairs and doors are a problem with build 936 as well, because there has been a related change in build 937.

**Comment by asofold** [comment] 2016-03-06 12:28
Can't reproduce acacia doors and purple stairs with NCP build 937 and yesterdays spigot. Will retry with latest spigot build.

Could you give more details?
* Output of the 'ncp version' command (text much preferred).
* More details about which and how to setup blocks/doors?

**Comment by partydragen** [comment] 2016-03-06 12:33
Running latest version of NCP Build and Spigot Updated every things before i checked again and its looks Doors and Purpur Stairs works again

**Comment by partydragen** [comment] 2016-03-06 12:43
i think i used wrong build yesterday since i had Nocheatplus (1) and Nocheatplus i think i updated with 9​36 instant of 9​37

I have already removed NCP again to lett people use elytra and skulker effect so can't run the command now

**Comment by asofold** [comment] 2016-03-07 22:17
So i assume this is fixed already then.

**Closed** 2016-03-07 22:17 UTC
Labels: (a) false positive, (c.1) moving, (p.1) NoCheatPlus, (r.1) resolved
