### ISSUE TITLE
Stuck in blocks (survivalfly) [DBO 730]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#30] opened 2015-12-06 11:15 UTC
==What is the problem? What do you expect to see instead?==

The problem is that some players are being kicked for flying, while they are actually stuck inside a block. This makes them unable to play on the server, as they are kicked every time they log in.

==Can it be reproduced systematically and if so: How?==

There are multiple ways, examples are:

A water melon happens to grow on the spot you are standing, causing the player to be stuck as described above.
A cobblestone spawns exactly where the player stands (cobblestone generator in SkyBlock)
Clip into a wall otherwise (enderpearl, pistons?).
==How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?==

It happens with vanilla clients. It only happens under rare circumstances as described above, but more than a dozen players have already reported this.

==Versions of NCP and server: Post the output of the "ncp version" command!==

Spigot 1356

NCP 3.10.9

==Details about the configuration file of NCP.==

Default config

==Do you run any other special plugin next to NC+ (adding skills, machines, adding/changing blocks)?==

No

![jqwfm31](https://cloud.githubusercontent.com/assets/1159235/11613053/643d9f28-9c13-11e5-8748-5a33d615c518.png)
![qkk3x9j](https://cloud.githubusercontent.com/assets/1159235/11613052/643c5140-9c13-11e5-980d-e04d4d1631a5.png)

**Comment by MyPictures** [comment] 2015-12-06 11:15
**asofold:** "Someone needs to re-test this one, could be that an extra check in isOnGround has been removed and leads to this.

Assume a good test is to let sand fall down or vegetables grow on the players position."

**Comment by asofold** [comment] 2015-12-29 00:11
This might be fixed now (small range tp removed, better past move data).

**Comment by Blackyvk** [comment] 2016-04-10 01:30
I'm still getting this problem

when they logout on carpets or corners, I even saw one getting stuck in a corner while swimming, it took me a while finding a way to reproduce it.

You logout on the carpet near the corner and when you log in you get stuck triggering infinite warnings. 
![carpet](http://i.imgur.com/9NBBopb.png)

Here is the debug
http://pastebin.com/NG8PH0Zx

Tell me If you need more logs or tests.

**Comment by MyPictures** [comment] 2016-04-10 06:46
awesome thank you @Blackyvk

**Comment by asofold** [comment] 2016-04-11 00:38
That looks like mc server moving players outside of blocks in excess. Will have to study more in depth...

**Comment by asofold** [comment] 2016-06-15 11:13
Does anything like this persist with latest NCP (1013+)?

**Comment by asofold** [comment] 2017-05-02 21:16
Assume superseded (by ages), there are new fixes pending for passable and other related stuff has changed, thouhg.

**Closed by asofold** 2017-05-02 21:16 UTC
Labels: (a) bug, (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus, (q) need reproduce, (q.2) IMPORTANT, (r) fixed, (r) superseded
