### ISSUE TITLE
1.9: Building up in the air causes survivalfly false-positives

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#99] opened 2016-03-04 01:01 UTC
00:23:27 INFO: ---- Version information ----
00:23:27 INFO: #### Server ####
00:23:27 INFO: git-Spigot-dd155ed-3e3516e ~MC: 1.9~
00:23:27 INFO: detected: 1.9
00:23:27 INFO: #### NoCheatPlus ####
00:23:27 INFO: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b933
00:23:27 INFO: MCAccess: 1.9 / Spigot-CB-1.9_R1

00:23:27 INFO: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
00:23:27 INFO: checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
00:23:27 INFO: defaults: pvpKnockBackVelocity
00:23:27 INFO: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
00:23:27 INFO: Hooks: AllViolations~NCP~ 1.0
00:23:27 INFO: #### Related Plugins ####
00:23:27 INFO: ProtocolLib v3.7-SNAPSHOT-b239

![2016-03-04_02 00 04](https://cloud.githubusercontent.com/assets/13700636/13514891/0e5c13ca-e1ad-11e5-93e5-dc4567212994.png)

**Comment by asofold** [comment] 2016-03-04 10:13
Please update Spigot (note: https://hub.spigotmc.org/jira/browse/SPIGOT-1646)! And do keep checking for updates (also note: https://twitter.com/Spigot_MC).

Current Spigot when writing this comment (soon to be outdated): git-Spigot-87e2f47-ef13ca4

(I hope you don't mind the copy and paste :).)

**Comment by Platinteufel** [comment] 2016-03-04 11:44
My spigot version contains this patch, I was running the latest build (11h ago now). But I will update again soon.

**Comment by asofold** [comment] 2016-03-04 11:55
I might've overlooked that your version is somewhere between, at least you need this change in: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/CraftBukkit/commits/31caee5a947

Confirmed: "Noob tower" (up) is an issue with latest.

**Comment by asofold** [comment] 2016-03-04 13:13
(Not resolved in build 934, looks like the placed block is missing internally, possibly order of processing move vs. block place.)

**Comment by Her-Craving** [comment] 2016-03-21 20:09
Is this being worked on?

**Comment by AgentLV** [comment] 2016-03-22 10:42
This is still a problem with the latest spigot.
#### Server ####
git-Spigot-unknown-616a968 ~MC: 1.9~
  detected: 1.9
#### NoCheatPlus ####
Plugin: 3.14.0-SNAPSHOT-sMD5NET-b954
MCAccess: 1.9 / Spigot-CB-1.9_R1
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.0.0-SNAPSHOT-b266

http://hastebin.com/ovuqayixiv.vhdl

**Comment by Gioboi** [comment] 2016-03-22 17:05
I would really appreciate if this is put as a high priority! Thanks!

**Comment by asofold** [comment] 2016-03-22 17:54
Since elytra about works, this'll be about next.

**Comment by Gioboi** [comment] 2016-03-22 17:56
Thanks!

**Comment by asofold** [comment] 2016-03-24 09:28
Can a fix be confirmed (build 955 about)?

**Comment by Gioboi** [comment] 2016-03-24 21:41
Its fixed ty. still getting many NoSwing false positives on a side note

**Comment by asofold** [comment] 2016-03-24 22:48
Ok :), i'll close this very issue then. NoSwing is another thing, could use a review of the noswing concept.

**Closed by asofold** 2016-03-24 22:48 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p.1) NoCheatPlus, (r.1) fix verified
