### ISSUE TITLE
FastHeal enabled, despite shouldn't.

### ISSUE THREAD

**Issue by mibby** [NoCheatPlus/Issues#533] opened 2018-04-11 11:20 UTC
NoCheatPlus as of commit https://github.com/NoCheatPlus/NoCheatPlus/commit/cbfcecf2b49de24694a0335ff4e4eb821ca64cf2

```
    fastheal:
      active: true
      interval: 4000
      buffer: 1000
      actions: cancel vl>10 cmdc:fastheal1:1:15 cancel vl>45 cmdc:fastheal2:1:12 cancel
```

Whenever someone eats in one of my arenas (duel in my case), they throw out FastHeal violations. The arena has hunger enabled and food eating is _not_ instant use/restore. Eating outside the arena, no violations occur.

Is the check currently broken?

**Comment by asofold** [comment] 2018-04-11 18:22
Given that the false positives only amass inside of arenas, i'd rather suspect an incompatibility of some kind - very likely the arena plugin forestalls/alters/fires-custom(/double/instead+-) events.

If this is very easy to reproduce i'd appreciate a debug log for a player - with build 1144 or better from the given commit on, you can pinpoint debug to several check groups (/checks).
* /ncp debug player PLAYERNAME_OR_UUID yes:INVENTORY:FIGHT

Later:
* /ncp debug player PLAYERNAME_OR_UUID default

(All provided the command works at all :p - the build has undergone a lot of changes, but none other than data/config-getting changes concerning fastheal. INVENTORY should be added, to get some info on item consumption and order of those things in the log. Wiki hasn't been updated to reflect these changes yet.)

(Edit: It's still _/ncp debug player PLAYERN..._)

**Comment by ScuroK** [comment] 2018-05-06 11:11
@asofold recently im getting tons of false positives about fast heal even they are not in any arena!
can you fix this please?

**Comment by asofold** [comment] 2018-05-07 08:18
Indeed the FastHeal check should be disabled since MC 1.9 - that's why the output of 'ncp version' is more idiot-proof, because i can't forget those aspects as easily.

In this case we need to know what "detected: ..." is showing (UNKNOWN or 1.12.2/whatever)...

**Comment by asofold** [comment] 2018-05-07 08:35
Since the other ticket has 'ncp version' i'll close this one as a duplicate. Feel free to ~~comment~~ _object_.

**Closed as completed by asofold** 2018-05-07 08:35 UTC
Labels: (r.2) duplicate, (a) false positive, (c.1) fight+health, (c) gameplay/experience, (p) compat/external, (p.1) NoCheatPlus
