### ISSUE TITLE
Kicked for flying

### ISSUE THREAD

**Issue by cloakfox** [NoCheatPlus/Issues#61] opened 2015-12-24 23:38 UTC
Basicly the issue is that players on my server are getting kicked for flying while they are not. (Might be caused by lag spikes, and then ncp freaking out and kicking the player)

"So I was building on survival and I placed a stair block under me and then I got kicked for flying. I tried to relog but it keeps kicking me for flying" -Quote from one of my players.
Reports like the one above are often posted on my forums.

I have heard this issue occur many times on my server. Also a lot on my creative server with things like stairs, fences, boats (on break).

Are the most reported causes of the kicked for flying issue. This has been happening for as long as I can remember using ncp xd.

There is not much info on how to re-produce this bug/issue.
I do know it happened on the survival server wich is running the following versions: http://imgur.com/10cBQLx

I often fix this issue by letting the player join in for example 5 seconds, then I quickly join the server that the fly bug occured on and wait for the player to log in and tp him or her to spawn. (What I have been doing for ages now, and is quite frankly anoying as heck).

**Comment by asofold** [comment] 2015-12-25 00:06
I'll attempt to reproduce on default Spigot.

**Comment by asofold** [comment] 2015-12-26 11:02
I found 'something' with stairs, possibly not related to this issue, but 'some' alteration/fixes will certainly follow from this. Will note here once something has been done.

**Comment by cloakfox** [comment] 2015-12-26 12:50
Alright thanks!

**Comment by asofold** [comment] 2015-12-28 23:48
Build 907 contains changes that might resolve this issue. Can't be 100% sure though, and it might contain other/new issues.

**Comment by asofold** [comment] 2016-01-01 00:23
Possibly prefer build 908.

**Comment by asofold** [comment] 2016-01-01 22:01
Are you using AuthMe (/Reloaded)?

**Comment by cloakfox** [comment] 2016-01-01 22:04
No
Op 1 jan. 2016 23:01 schreef "asofold" <notifications@github.com>:

**Comment by asofold** [comment] 2016-01-01 22:04
Are people kicked only after trying to log in again, or also right after jumping onto the placed block?

**Comment by cloakfox** [comment] 2016-01-02 15:56
No when they log back in, they are still on that block so get kicked right
after, they can't move either.

2016-01-01 23:04 GMT+01:00 asofold <notifications@github.com>:

**Comment by Iceee** [comment] 2016-01-02 18:50
Can you post the output of /ncp version please?

**Comment by Iceee** [comment] 2016-01-02 18:53
Can you show us the logged violations of the players in question around that time?  Check in the NoCheatPlus directory in your plugins directory.

**Comment by asofold** [comment] 2016-01-03 00:06
@cloakfox Does this change with build 909 (violations or /ncp info player or gone completely, etc)?

**Comment by asofold** [comment] 2016-01-03 11:57
@cloakfox Actually Build 910 might fix this.

**Comment by cloakfox** [comment] 2016-01-03 12:10
Alright will try that build out.

2016-01-03 12:58 GMT+01:00 asofold <notifications@github.com>:

**Comment by Mikgreg** [comment] 2016-01-06 17:41
Hey, to add onto this NCP + SpawnTP is causing a lot of false positives. 

When you set a spawn point with SpawnTP it actually sets it a little bit in the air to create a dropping down effect, after updating to build 912 all the players in my lobby started getting kicked for flying because of this dropdown effect.

http://i.imgur.com/nak4qVd.png

**Comment by asofold** [comment] 2016-01-06 22:39
@Mikgreg Thank you for noting that quickly - does build 913 fix that?

**Comment by Mikgreg** [comment] 2016-01-07 17:08
This seems to be fixed now, thanks!

**Comment by asofold** [comment] 2016-01-11 23:33
Assume fixed. Please note, if issues persist past build 915.

**Closed** 2016-01-15 19:29 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p) compat/external, (p.1) NoCheatPlus, (q.2) IMPORTANT, (r) fixed
