### ISSUE TITLE
Using elytra: bounding box height differs!

### ISSUE THREAD

**Issue by PoisonedPorkchop** [NoCheatPlus/Issues#303] opened 2016-11-08 08:05 UTC
#### Short description of the issue.
When using elytra wings, the player's height has "a shorter hitbox than usual: 0.6 blocks in height rather than 1.8 blocks." as quoted from http://minecraft.gamepedia.com/Elytra. The vector checks, such as the Passable and Visible checks, do not take this into account. As a result, flying directly under ledges will clip players, but more importantly making this feature https://www.youtube.com/watch?v=org8scu998c impossible without turning off the Passable check, and actually doing anything impossible without disabling the Visible check.
#### Complete output of the _ncp version_ command (please prefer text here).
---- Version information ---- (Slightly edited to remove formatting problems)
//#### Server ####
git-Spigot-047f737-744e1a1       MC: 1.10.2
   detected: 1.10.2
//#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1030 (However I tried this on many builds)
MCAccess: 1.10 / Spigot-CB-1.10_R1
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations    NCP 1.0
//#### Related Plugins ####
ProtocolLib v4.1.0
#### How to reproduce the issue (is it random / always happens / side conditions)?
For non operator players, it always happens.
#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
On the main server on which I first encountered this, it was heavily modified. However, on a "vanilla" test server with just NCP, it still occurred. This is an oversight of NCP, not caused by other plugins.

**Comment by asofold** [comment] 2017-04-30 19:49
Could someone reproduce this with debug logging on?

**Comment by asofold** [comment] 2017-05-03 14:14
Adjusting the visible check would be simple.

For passable this remains a problematic thing, because it'll allow players to clip into blocks on stopping using the elytra, or getting through narrow spots where you can't fly through. Adjustments to prevent these things are potentially complicated to do (rather complicated to roll back).

**Comment by asofold** [comment] 2017-05-07 13:02
Build 1101 contains a first fix for this. It's not complete, e.g. you'll still get stuck in web (without boost only) if you fly just underneath.

Suggest: build 1104

**Closed** 2017-05-30 21:39 UTC
Labels: (a) bug, (c.1) moving, (p.1) NoCheatPlus, (q) need debug log, (r) fixed
