### ISSUE TITLE
KillAura hack

### ISSUE THREAD

**Issue by UlisesOcana** [NoCheatPlus/Issues#352] opened 2016-12-23 23:56 UTC
#### Short description of the issue.
Hits near entity and its almost undetectable for ncp!

**Comment by MarkElf** [comment] 2016-12-24 00:30
Did you really have to create a duplicate of an open issue just below this one that does not contribute anything?

Please refer to #349.

**Comment by MarkElf** [comment] 2016-12-24 00:33
Did you really have to create a duplicate of an open issue just below this one that does not contribute anything? I get that kill-aura is a "hot topic" but we don't need multiple open tickets covering the same content.

Please refer to #349.

**Comment by asofold** [comment] 2016-12-24 14:00
It does duplicate at least one existing issue :).

**Closed by asofold** 2016-12-24 14:00 UTC
Labels: (r.2) duplicate
