### ISSUE TITLE
Survival fly on lilypads, carpet, and slabs

### ISSUE THREAD

**Issue by Theepwner** [NoCheatPlus/Issues#274] opened 2016-09-07 08:10 UTC
So basically, running and jumping on lilypads is quite annoying and glitchy. You can also trigger survival fly on other surfaces such as carpet and when maneuvering around slabs. The lilypads are the real issue though. Try set up a pool of water and place lilypads all around, jump on and off them in as many ways as possible and you will see the issue. (idk why but putting 2 lilypads right next to each other and going on them will be even more glitchy). You can also trigger checks by swimming and getting back on the lilypads.

Running a near default config that doesn't adjust the movement checks.
ver #1022 on latest paperspigot 1.8.8

Sorry for the bad description but it shouldn't be too hard to see.

**Comment by RoboMWM** [comment] 2016-09-08 20:34
Need /ncp version, as well as plugins you're running (specifically if you're running viaversion, protocolsupport, or any other protocol-hacking plugin)

**Comment by Theepwner** [comment] 2016-09-09 06:58
http://prnt.sc/cfwlcf

Viaversion that allows 1.8-1.10. Server is 1.8.

**Comment by RoboMWM** [comment] 2016-09-09 19:09
Well viaversion is likely the issue here, since I guess the block sizes are somewhat different on 1.9+ clients.

Nothing much you can do about this afaik other than updating or not using viaversion

**Comment by Katon151998** [comment] 2016-09-19 16:53
I don't have viaversion...

**Comment by hurrgurl** [comment] 2016-10-03 04:53
Same issue here, can not walk on lily pads. (survivalfly doesnt like it)

[00:45:39 INFO]: git-Paper-837 ~MC: 1.10.2~
[00:45:39 INFO]:   detected: 1.10.2
[00:45:39 INFO]: #### NoCheatPlus ####
[00:45:39 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1022
[00:45:39 INFO]: MCAccess: 1.10 / Spigot-CB-1.10_R1

**Comment by RoboMWM** [comment] 2016-10-03 04:57
@hurrgurl Are you using viaversion? If so, refer to my previous comment.

**Comment by L4BORG** [comment] 2016-10-09 01:07
There could be a list of blocks (Materials) in config that would be excluded/exception? It would be better solutions than disabling survivalfly or letting players glitch.

**Comment by RoboMWM** [comment] 2016-10-09 01:21
Or not use viaversion.

> There could be a list of blocks (Materials) in config that would be excluded/exception?

You could make a plugin hook into NCP and do this if you so desire - but I don't think adding bandaids in the main plugin is good idea.

**Comment by asofold** [comment] 2016-11-01 11:56
For individual blocks you can always try adding to compatibility.blocks.overrideflags, using bukkit material names (not minecraft!) or default block ids (see wiki).
Example:
WATER_LILY: default+GROUND_HEIGHT+IGN_PASSABLE+HEIGHT100

HEIGHT100 is horrible, because it'll trigger lowjump detection and let bunny hopping fail on longer trails of lily pads - can't test myself if you can do without HEIGHT100 with differing client versions connected.

Possibly i'll add a hack flag like ALLOW_LOWJUMP, will need to investigate. Currently i don't plan to have client specific block shapes (...), but never know where things may go.

**Comment by asofold** [comment] 2016-11-01 12:48
Using build 1025 http://ci.md-5.net/job/NoCheatPlus/1025/ or later, you might be able to work around the lily pad issue:
Add to the configuration at compatibility.blocks.overrideflags:
WATER_LILY: default+ign_passable+ground_height+height8_1

**Comment by Sitmobedaf** [comment] 2016-11-01 13:38
https://youtu.be/MJoyxlVTmrM

**Comment by L4BORG** [comment] 2016-11-04 18:52
@asofold meaning? Should we use 

compatibility.blocks.overrideflags: WATER_LILY: default+ign_passable+ground_height+height8_1

if we're running spigot(paper)1.8 with ViaVersion? And this would resolve false kicks for flying on lilys?

**Comment by asofold** [comment] 2016-11-05 21:17
What with carpet and slabs? I might've failed to reproduce, but it can be done similarly (might need other flags for slabs, if so).

**Comment by RoboMWM** [comment] 2016-11-21 21:42
Unless I'm doing something wrong, it seems that lily pads aren't playing nice with NCP in CB 1.11 (build 1030). However, using this line

> WATER_LILY: default+ign_passable+ground_height+height8_1

seems to have resolved it - I'm guessing then this is a loose check, not a specific 1.8 height check?

(By the way, I do not use viaversion or other protocol hacks, I only posted here because of the relevant option that helped fix an issue with the current NCP build on MC 1.11)

**Comment by asofold** [comment] 2016-11-21 22:20
@RoboMWM It should be:
water_lily: default+ground+ground_height+height8_1

I forgot to add ign_passable for testing, which appeared to work, it should be safe to add that as well. Looks like it's not setting it as ground.

**Comment by asofold** [comment] 2017-05-02 20:43
Lilypad is a default, if ProtocolSupport or ViaVersion is present.
Not sure about carpets. GRASS_PATH may remain to be tackled otherwise.

Closing as 'resolved' for now, though default activations  for (proper) workarounds would be nice to have.

**Closed by asofold** 2017-05-02 20:43 UTC
