### ISSUE TITLE
Kicked for Flying

### ISSUE THREAD

**Issue by Mikgreg** [NoCheatPlus/Issues#71] opened 2016-01-15 14:08 UTC
Hi, this issue is different from the last "kicked for flying" bug I reported. Recently A LOT of my players are getting the "Kicked for flying (or related)" message, a lot of my players are unable to log in due to it as they get kicked straight away on login.

It's being triggered by stuff as small as getting out of a boat, or getting off of a horse, among other things. 

Please let me know how I can aid in troubleshooting and resolving this issue, my fly settings in the config are default right now, I'm running NCP version 3.13.5-SNAPSHOT-sMD5NET-b913.

I'm running this on Paperspigot, version:
http://i.imgur.com/6OF1BPE.png

The only output in console when this happens is
> Player joined the game
> Player disconnected: Kicked for flying (or related)

**Comment by asofold** [comment] 2016-01-15 19:35
The other issue is closed now.

We need to be very precise here, to distinguish the various cases.

1. Is it only about vehicles (boats, horses, ... pigs?)?
2.  Are any plugins/features in use letting people ride unusual entities?
3. If it is not only about dismounting ... what else (perhaps needs another ticket)?

For some entities one might have vehicle move events, for some not, for some we might have player move events. My guess is player move events firing due to latency "simply", so after (forced) dismount the events arrive and represent a big leap - doesn't explain the kicking at all.

Could you re-post the full output of '/ncp version' ? You could use the client log for text copy and paste, in any case just add it here.

**Comment by Mikgreg** [comment] 2016-01-16 19:57
1. No, players have reported it happening to them if they log off while mining, they will join again and get kicked for flying. 

Another common case is the use of AFK machines, water pushes you onto a fence and you bounce there, logging in here gets you kicked for flying. 

I'm trying to get more cases but they're pretty diverse. You don't even have to move up a quarter of a block to get kicked for flying.

We don't have any unsual entities, or riding of them. This is also not just about dismounting.

http://i.imgur.com/uIXq8o6.png

**Comment by asofold** [comment] 2016-01-17 01:47
The violation level would accumulate for a part, so it won't always just reflect the distance taken. Repetition will lead to kicking at some point.

Did you update PaperSpigot since? Will test fence and some other things tomorrow. Any kind of debug logs / messages with [tags] much welcome...

**Comment by Mikgreg** [comment] 2016-01-17 20:58
[15:38:58] [Craft Scheduler Thread - 398/INFO]: [NoCheatPlus] The_Number_One failed SurvivalFly: tried to move from -2634.97, 14.71, 54.61 to -2634.97, 14.22, 54.61 over a distance of 0.49 block(s). VL 419.
[15:39:03] [Craft Scheduler Thread - 398/INFO]: [NoCheatPlus] The_Number_One failed SurvivalFly: tried to move from -2634.97, 14.22, 54.61 to -2634.97, 14.12, 54.61 over a distance of 0.10 block(s). VL 930.
[15:39:13] [Craft Scheduler Thread - 381/INFO]: [NoCheatPlus] The_Number_One failed SurvivalFly: tried to move from -2634.97, 14.31, 54.61 to -2634.97, 14.51, 54.61 over a distance of 0.20 block(s). VL 967.

[15:39:17] [Craft Scheduler Thread - 398/INFO]: [NoCheatPlus] The_Number_One failed SurvivalFly: tried to move from -2634.97, 14.31, 54.61 to -2634.97, 14.41, 54.61 over a distance of 0.10 block(s). VL 1510.
[15:39:17] [Server thread/INFO]: The_Number_One lost connection: Kicked for flying (or related)
[15:39:17] [Craft Scheduler Thread - 398/INFO]: [NoCheatPlus] (CONSOLE) Kicked The_Number_One : Kicked for flying (or related)

This is happening as they log in, it has happened across many Paperspigot versions.

**Comment by asofold** [comment] 2016-01-19 23:11
I managed to get a (short-ish) set back loop with breaking blocks underneath me (pilar) on build 908, but no with around 920. Does it change with build 920 (i assume maybe not, as this probably isn't the same)?

**Comment by Mikgreg** [comment] 2016-01-20 15:07
Its not just breaking blocks, I'm really unsure what is causing it o_o', we keep on getting a huge variety of different circumstances its happening in, it's really a widespread issue, the blank kicks on this list is the instances of people getting kicked for flying:

https://forum.omegarealm.com/bans/history.php?uuid=CONSOLE&staffhistory=1

I'll try updating. Sorry for not being descriptive but every person I ask gives a different situation.

**Comment by MyPictures** [comment] 2016-01-23 22:01
I cannot reproduce on:
21:40:35 INFO: ---- Version information ----
21:40:35 INFO: #### Server ####

21:40:35 INFO: (detected: 1.8.8)
21:40:35 INFO: #### NoCheatPlus ####
21:40:35 INFO: Plugin: 3.13.6-SNAPSHOT-sMD5NET-b920
21:40:35 INFO: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3

21:40:35 INFO: blocks: BlocksMC1_4(base) | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
21:40:35 INFO: checks: FastConsume | Gutenberg
21:40:35 INFO: defaults: pvpKnockBackVelocity
21:40:35 INFO: Hooks: AllViolations(NCP) 1.0 | TestNCPHook 1.0

Does it happen to yourself too? (You can let NC+ check you even as a admin).

**Comment by asofold** [comment] 2016-01-24 22:12
@MyPictures The server version seems to be missing :). I think it was latest PaperSpigot at that point of time.

**Comment by MyPictures** [comment] 2016-01-25 17:50
@asofold ahh darn strange... Yeah it was paperspigot.

**Comment by asofold** [comment] 2016-01-26 09:24
@Mikgreg To progress i think we need to  get a debug log from your server, can it be reproduced more or less at will?

**Comment by asofold** [comment] 2016-06-13 19:58
Should've asked if loadchunks: join was activated and if players get teleported on join (+leave).

A couple of changes have been made, specifically for teleportation/moving. Could well be we have to close, because too much changed, unless the issue persists...

**Comment by asofold** [comment] 2016-06-15 10:26
Closing as 'superseded', as some changes have been made to both sides. Please comment, re-open or open a new issue, if the issue persists in any way.

**Closed by asofold** 2016-06-15 10:26 UTC
Labels: (a) false positive, (c) gameplay/experience, (c.1) moving, (p) compat/external, (p.1) NoCheatPlus, (q) need debug log, (q) need reproduce
