### ISSUE TITLE
Abnormal SurvivalFly levels

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#367] opened 2017-01-08 23:39 UTC
In the last weeks there where more and more people that keep getting kicked for flying.
A short look into the log files shows that there must be some cases where the SurvivalFly level increases abnormal: http://pastebin.com/wWbe3AvE

Relevant part:
    Line 21879: 17-01-08 20:37:31 [INFO] Morgwin failed SurvivalFly: tried to move from -1423.13, 9.00, -315.95 to -1423.16, 9.00, -315.93 over a distance of 0.04 block(s). **VL 547**.
    Line 21880: 17-01-08 20:37:32 [INFO] Morgwin failed SurvivalFly: tried to move from -1423.13, 9.00, -315.95 to -1423.22, 9.00, -316.02 over a distance of 0.12 block(s). **VL 9223372036854775807**.

I asked the player if something is wrong with the internet connection or framerate, but his ping was 10ms and the framerate was fine too.
There were also 5 other cases where players got kicked a lot of times - also with abnormal SurvivalFly levels.

Unfortunately I don't know yet what causes this behaviour, but maybe you have some thoughts about it.
Thanks!

```
[00:30:24 INFO]: ---- Version information ----
[00:30:24 INFO]: #### Server ####
[00:30:24 INFO]: git-Paper-916.2 ~MC: 1.10.2~
[00:30:24 INFO]:   detected: 1.10.2
[00:30:24 INFO]: #### NoCheatPlus ####
[00:30:24 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1053
[00:30:24 INFO]: MCAccess: 1.10-1.10.2 / Spigot-CB-1.10_R1
[00:30:24 INFO]: Features:
[00:30:24 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
[00:30:24 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[00:30:24 INFO]:   defaults: pvpKnockBackVelocity
[00:30:24 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[00:30:24 INFO]: Hooks: AllViolations~NCP~ 1.0
[00:30:24 INFO]: #### Related Plugins ####
[00:30:24 INFO]: ProtocolLib v4.2.0-SNAPSHOT-b329
```
& default config

**Comment by asofold** [comment] 2017-01-10 18:22
That's very odd... couldn't find a potential cause by conde inspection, yet.

**Comment by Platinteufel** [comment] 2017-01-11 03:00
_"just after world change"_ .. I think you got it. After taking a look into the serverlog files again I may can describe it in more detail:
In some rare cases players are bugging on login and can't move if they logged out on some special places (and somtimes because of AuthMe Reloaded). Because of that I cancle the ncp-kick if they are not longer than _15 seconds_ online and sent them to spawn instead (in those special cases **into another world**). It seems like NoCheatPlus gives those players abnormal SurvivalFly-levels on (or just after) this world change (it actually wanted to kick them).

**Comment by CaptainObvious0** [comment] 2017-01-21 05:06
Got a new addition to the issue:

I currently run a config that aims to improve NoCheatPlus. One of its features is an Auto-Ban config. One of my users reported the exact issue reported here. Same VL level, and they had AuthMe installed on the server.

Here's the logs from the server:
`[12:06:35] [User Authenticator #15/INFO]: UUID of player Necroboi is b05ae967-7031-3eaa-95d8-e14ace27ac9e
[12:06:35] [Server thread/INFO]: Necroboi[/removed] logged in with entity id 449825 at ([world]-1659.434506685007, 64.0, 2569.3234870612296)
[12:06:43] [Server thread/INFO]: [ConditionalCommands] Successfully parsed expression: ((22.0 > 151.0) | (19.9700449326011 < 19.0))
[12:06:43] [Server thread/INFO]: [ConditionalCommands] > Dispatching command "ban Necroboi &8[&cNCP&8] &cYou have been banned for hacking! "
[12:06:43] [Craft Scheduler Thread - 662/INFO]: [NoCheatPlus] AUTOBAN: The player Necroboi has been banned due to SurvivalFly (VL 9223372036854775807)
[12:06:43] [Craft Scheduler Thread - 665/INFO]: Necroboi has been permanently banned by Console for &8[&cNCP&8] &cYou have been banned for hacking!
[12:06:43] [Server thread/INFO]: Necroboi lost connection: §6You have been banned permanently for §4&8[&cNCP&8] &cYou have been banned for hacking!
[12:06:43] [Server thread/INFO]: Necroboi left the game`

My question is: How can we fix the issue now that we have identified the cause?

**Comment by asofold** [comment] 2017-01-22 19:51
I wouldn't say we've identified the cause yet :). We have two cases that have two side conditions in common, unless i am mistaken (after world change + authme).

The best thing to have would be a debug log for reproducing this issue (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players). That probably would get us there.

**Comment by Platinteufel** [comment] 2017-01-25 23:17
http://pastebin.com/2EgVxq35
Kick in line 8 have been cancelled (teleporting the player to spawn instead).

**Comment by asofold** [comment] 2017-01-25 23:33
@Platinteufel Could you post more context, sereval KB before the first of subsequent violations?

You could also zip larger parts and attach as file here...

Apparently it shows an infinite VL, which could hint at 'division by zero' or a return value not caught for a sub-method returning this somewhere (could also be multiplication with that, e.g. getEffect(...) returns infinity meaning no effect, then multiply). We do need the log much before the violation too! A rule of thumb is like at least the last move touching ground before the violation plus 20 or so moves. In case of issues with repeated sprint jumping we might need even more (due to buffer depleting very slowly on occasion). So best guess is to zip/post a lot :).

**Comment by Platinteufel** [comment] 2017-01-25 23:44
[ncplog.zip](https://github.com/NoCheatPlus/Issues/files/731205/ncplog.zip)
That's the hole context, starting on player-join. :)

I logged out on water so that I was bugging on login (AuthMe+water -> not a good combination because AuthMe tries to freeze the player)

**Comment by asofold** [comment] 2017-01-28 21:20
That's interesting, so one of the subsquent violations (not the first!) made the  VL infinite.

**Comment by asofold** [comment] 2017-02-25 23:24
Is this fixed with build 1066?

**Comment by asofold** [comment] 2017-04-21 11:36
Assume fixed. Please drop a note if not :).

**Closed by asofold** 2017-04-21 11:36 UTC
Labels: (a) bug, (a) false positive, (c) gameplay/experience, (c.1) moving, (q.2) IMPORTANT
